const GLOSSARY_DATA = {
            "fihr": { origin: "Généalogie", def: "Ancêtre commun de la tribu de Quraysh." },
            "ouhoud": { origin: "Bataille (An 3 H)", def: "Bataille éprouvante au pied du mont Ouhoud, où le Prophète fut blessé et de nombreux compagnons tués (dont Hamza et Mouss'ab)." },
            "dounia": { origin: "Concept", def: "La vie d'ici-bas, éphémère et matérielle." },
            "amwas": { origin: "Lieu", def: "Village de Palestine (Emmaüs), foyer d'une épidémie historique." },
            "taym": { origin: "Tribu", def: "Clan de Quraysh, famille d'Abou Bakr et Talha." },
            "al-fayyad": { origin: "Surnom", def: "« Le Torrent » ou « Le Brave », qualifiant une générosité abondante." },
            "al-jamal": { origin: "Histoire", def: "La « Bataille du Chameau » (36 H), conflit tragique entre compagnons." },
            "badr": { origin: "Bataille (An 2 H)", def: "Première grande bataille de l'Islam. Ses vétérans ont un rang très élevé." },
            "badriyun": { origin: "Groupe", def: "Les compagnons ayant participé à la bataille de Badr. Ils ont un statut très élevé en Islam." },
            "najran": { origin: "Lieu", def: "Ville du Yémen dont les chrétiens vinrent voir le Prophète." },
            "saqifa": { origin: "Lieu", def: "Jardin des Banu Sa'ida où fut décidé le Califat après la mort du Prophète." },
            "sham": { origin: "Géographie", def: "Le Levant (Grande Syrie)." },
            "qourashite": { origin: "Tribu", def: "Membre de la tribu de Quraysh, la tribu dominante de La Mecque." },
            "mouhajirounes": { origin: "Groupe", def: "Les Émigrés de la Mecque vers Médine." },
            "mouhajir": { origin: "Terme", def: "Un Émigré (singulier de Mouhajirounes)." },
            "safiya": { origin: "Famille", def: "Safiya bint Abdelmoutalib, tante paternelle du Prophète, mère de Zoubayr et sœur de Hamza." },
            "hawari": { origin: "Titre", def: "Titre honorifique signifiant 'Apôtre' ou 'Ami intime' qui porte secours." },
            "fitna": { origin: "Histoire", def: "La grande sédition qui opposa les compagnons après la mort d'Othman." },
            "zouhri": { origin: "Tribu", def: "Du clan Banu Zuhra, le clan de la mère du Prophète (Amina)." },
            "shura": { origin: "Concept", def: "Conseil consultatif. Ici, le comité de 6 compagnons désigné par Omar pour élire le Calife." },
            "tabouk": { origin: "Expédition (An 9 H)", def: "Dernière grande expédition du Prophète, dans des conditions difficiles." },
            "al-qadisiyya": { origin: "Bataille (15 H)", def: "Bataille majeure marquant la chute de l'Empire Perse face aux musulmans." },
            "banou zouhra": { origin: "Tribu", def: "Clan de Quraysh auquel appartenaient Saad et Amina, la mère du Prophète." },
            "ctésiphon": { origin: "Lieu", def: "Capitale de l'Empire Perse Sassanide (aussi appelée Al-Madaïne)." },
            "abou waqas": { origin: "Personnage", def: "Père de Saad, de son vrai nom Malik ibn Ouhayb." },
            "adawi": { origin: "Tribu", def: "Du clan des Banou Adi, le même clan qu'Omar ibn Al-Khattab." },
            "oumar": { origin: "Personnage", def: "Oumar ibn Al-Khattab, 2ème Calife." },
            "damas": { origin: "Ville", def: "Ville du Sham (Syrie) dont Saïd fut le premier gouverneur musulman." },
            "houdaybiya": { origin: "Lieu", def: "Lieu du célèbre pacte de paix (6 H) entre le Prophète et les Qurayshites." },
            "arwa": { origin: "Personnage", def: "Arwa bint Ouways, la femme qui accusa faussement Saïd et subit son invocation." },
            "yamama": { origin: "Bataille (12 H)", def: "Bataille féroce contre Musaylima le Menteur (guerre d'apostasie) où beaucoup de recitateurs du Coran moururent." },
            "baqi": { origin: "Lieu", def: "Cimetière principal de Médine où reposent de nombreux compagnons." },
            "idhkhir": { origin: "Botanique", def: "Plante aromatique (citronnelle) utilisée pour couvrir les pieds de Mouss'ab." },
            "abdari": { origin: "Tribu", def: "Du clan des Banu Abd ad-Dar, les porteurs de l'étendard de Quraysh." },
            "wahchi": { origin: "Personnage", def: "Esclave abyssin expert au lancer de javeline. Il tua Hamza contre la promesse de sa liberté." },
            "lion d'allah": { origin: "Titre", def: "(Asadullah) Titre honorifique donné à Hamza pour sa bravoure exceptionnelle." },
            "shushtar": { origin: "Ville", def: "Ville fortifiée de l'Empire Perse (Iran actuel), prise par les musulmans grâce à un souterrain." },
            "hunayn": { origin: "Bataille", def: "Bataille après la conquête de la Mecque où les musulmans furent d'abord surpris avant de se ressaisir." },
            "négus": { origin: "Titre Royal", def: "Titre porté par les souverains d'Abyssinie (Éthiopie). Le Négus Ashama fut celui qui protégea les musulmans." },
            "abyssinie": { origin: "Géographie", def: "Ancien nom de l'Éthiopie. Terre du premier exil (Hijra) des musulmans pour fuir la persécution." },
            "mouta": { origin: "Bataille (An 8 H)", def: "Bataille féroce contre l'Empire Byzantin où les trois généraux musulmans (Zayd, Jafar, Ibn Rawaha) moururent successivement." },
            "jibril": { origin: "Ange", def: "L'Archange Gabriel (Gabriel), chargé de transmettre la Révélation divine aux prophètes." },
            "mikail": { origin: "Ange", def: "L'Archange Michel (Michael), l'un des plus grands anges, souvent cité avec Jibril." },
            "asma bint oumays": { origin: "Famille", def: "Épouse de Jafar, elle émigra avec lui. Après la mort de Jafar, elle épousa Abou Bakr, puis Ali." },
            "fatima bint assad": { origin: "Famille", def: "Mère de Jafar et d'Ali. Elle a élevé le Prophète (ﷺ) comme son propre fils." },
            "sourate maryam": { origin: "Coran", def: "Chapitre 19 du Coran qui raconte l'histoire de Marie et Jésus, récité par Jafar devant le roi chrétien." },
            "zayd": { origin: "Compagnon", def: "Zayd ibn Haritha, fils adoptif du Prophète et premier commandant de la bataille de Mouta." },
	    "wasq": { origin: "Unité de mesure", def: "Unité de volume valant environ 60 jointées. Le Prophète en offrait 140 à 'Aqil chaque année." },
 	    "khaybar": { origin: "Lieu", def: "Oasis conquise par les musulmans (7 H). Lieu de production de dattes dont 'Aqil recevait une part." },
  	    "tihama": { origin: "Géographie", def: "Plaine côtière de la péninsule arabique. C'est là que Zayd fut capturé enfant par des cavaliers." },
 	    "al-batha": { origin: "Lieu", def: "Le lit du torrent à La Mecque, lieu de marché où Zayd fut vendu comme esclave." },
 	    "ansâb": { origin: "Croyance", def: "Pierres levées (bétyles) sur lesquelles les polythéistes sacrifiaient des bêtes avant l'Islam." },
  	    "al-aqaba": { origin: "Événement", def: "Serment d'allégeance prêté par les premiers musulmans de Médine (Ansar) au Prophète avant l'Hégire." },
 	    "khazraj": { origin: "Tribu", def: "L'une des deux grandes tribus de Médine (avec les Aws), dont faisait partie Abd-Allah ibn Rawaha." },
 	    "oumra": { origin: "Rite", def: "Petit pèlerinage à La Mecque. Ibn Rawaha y déclama des poèmes en entrant dans la ville sainte." },
  	    "ansar": { origin: "Groupe", def: "Les 'Auxiliaires', habitants de Médine ayant accueilli le Prophète. Ibn Rawaha en était un chef." },
	    "mouhadith": { origin: "Titre", def: "Savant spécialiste du hadith. 'Aqil était le grand-père d'un célèbre mouhadith." },
	    "hashimites": { origin: "Lignée", def: "Membres du clan des Banu Hashim, la famille noble du Prophète dont sont issus 'Aqil et Ali." },
   	    "al-ahzab": { origin: "Coran", def: "Sourate 33 « Les Coalisés ». C'est la seule sourate où un compagnon (Zayd) est cité nommément." },
	    "kalbien": { origin: "Tribu", def: "Membre de la tribu des Banu Kalb. Zayd était Kalbien avant d'être adopté." },
   	    "hira": { origin: "Lieu", def: "Cité historique d'Irak (sud de Koufa) où Zayd ibn 'Amr chercha la religion véritable." },
   	    "issaf et naïla": { origin: "Idoles", def: "Deux idoles de cuivre situées à Safa et Marwa que les polythéistes touchaient par dévotion." },
    	    "safa et marwa": { origin: "Lieu", def: "Deux collines près de la Kaaba. Zayd ibn Haritha refusa d'y toucher les idoles païennes." },
   	    "moursal": { origin: "Hadith", def: "Type de narration où la chaîne de transmission est interrompue (il manque le compagnon)." },
  	    "faqih": { origin: "Titre", def: "Savant spécialiste de la jurisprudence et de la législation islamique." },
    	    "haram": { origin: "Concept", def: "Territoire sacré (comme La Mecque). Oumar reprocha à Ibn Rawaha d'y réciter des poèmes de guerre." },
   	    "ma'an": { origin: "Lieu", def: "Ville du sud de la Jordanie où l'armée musulmane fit halte avant la bataille de Mouta." },
   	    "moab": { origin: "Lieu", def: "Ancien royaume (actuelle Jordanie) où l'armée byzantine s'était rassemblée contre les musulmans." },
   	    "byzantins": { origin: "Empire", def: "L'Empire romain d'Orient. Ils levèrent une armée de 100 000 hommes à la bataille de Mouta." },
            "al-yamama": { origin: "Bataille (12 H)", def: "Bataille majeure contre les tribus apostates et le faux prophète Musaylima, où de nombreux compagnons moururent." },
            "banou najjar": { origin: "Tribu", def: "Grand clan de Médine (Khazraj) dont As-Ad ibn Zourara était l'apôtre." },
            "banou al-achehal": { origin: "Tribu", def: "Clan des Ansar (Aous) réputé pour ses guerriers comme Saad ibn Mouadh et Oussayd ibn Houdayr." },
            "banou salima": { origin: "Tribu", def: "Clan des Ansar (Khazraj) dont Abd-Allah ibn 'Amr était l'apôtre." },
            "ajnadayne": { origin: "Bataille (13 H)", def: "Bataille en Palestine contre les Byzantins où de nombreux compagnons tombèrent en martyrs." },
            "yarmouk": { origin: "Bataille (15 H)", def: "Bataille décisive contre l'Empire Byzantin marquant la conquête du Sham." },
            "al-harra": { origin: "Bataille (63 H)", def: "Bataille tragique où l'armée omeyyade réprima une révolte à Médine, tuant de nombreux enfants de compagnons." },
            "moussaylima": { origin: "Personnage", def: "Surnommé « l'Imposteur », faux prophète qui mena la rébellion des apostats à Al-Yamama." },
            "qourashite": { origin: "Tribu", def: "Membre de la tribu de Quraysh (La Mecque)." },
            "ansarite": { origin: "Groupe", def: "Habitant de Médine ayant accueilli et soutenu le Prophète." },
            "makhzoumi": { origin: "Tribu", def: "Membre du clan Banu Makhzoum, clan puissant de Quraysh (celui d'Abou Jahl et Khalid ibn Walid)." },
            "omeyyade": { origin: "Dynastie", def: "Membre du clan Banu Umayya (comme Yazid ibn Abou Soufiane)." },
            "daous": { origin: "Tribu", def: "Sous-branche de la tribu Azd dont est issu At-Toufayl." },
            "basra": { origin: "Ville", def: "Ville d'Irak (Bassora) fondée par Outba ibn Ghazoine." },
	    "al-jabiya": { origin: "Lieu", def: "Ville du Sham (Syrie) où Oumar se rendit. Oussayd y commandait les Ansar." },
	    "bouzakha": { origin: "Bataille", def: "Lieu d'une bataille contre les apostats où Oukacha fut tué par Toulayha." },
	    "nahavand": { origin: "Bataille (21 H)", def: "Bataille décisive en Perse, surnommée « la Victoire des Victoires », où Toulayha mourut martyr." },
	    "serment de ridwan": { origin: "Événement (6 H)", def: "Serment prêté sous l'arbre à Houdaybiya par 1400 compagnons, jurant fidélité jusqu'à la mort." },
	    "banou saïda": { origin: "Lieu", def: "La Saqifa (préau) des Banu Sa'ida, lieu de réunion des Ansar après la mort du Prophète." },
	    "aqaba": { origin: "Lieu", def: "Monticule à Mina où les premiers Médinois prêtèrent allégeance au Prophète (serment d'Al-Aqaba)." },
  	    "doummar": { origin: "Lieu", def: "Village près de Damas où 'Oubada ibn As-Samit refusa de couper un saule par scrupule." },
   	    "barada": { origin: "Géographie", def: "Célèbre cours d'eau irriguant Damas et ses environs." },
   	    "ramla": { origin: "Ville", def: "Ville antique de Palestine où 'Oubada ibn As-Samit serait décédé." },
    	    "sahmite": { origin: "Tribu", def: "Membre du clan des Banu Sahm, branche de la tribu de Quraysh." },
    	    "césarée": { origin: "Ville", def: "Ville côtière (Qayssaria) où Abd-Allah ibn Houdhafa fut capturé par les Byzantins." },
    	    "ninive": { origin: "Lieu", def: "Cité antique près de Mossoul, lieu de naissance de Souhayb." },
    	    "ouboulla": { origin: "Lieu", def: "Cité portuaire perse (Apologou) où Souhayb grandit." },
    	    "namari": { origin: "Tribu", def: "Appartenant à la tribu arabe des An-Namir ibn Qasit (origine de Souhayb)." },
    	    "bayraha": { origin: "Lieu", def: "Palmeraie ou puits appartenant à Abou Talha, qu'il donna en aumône." },
    	    "tila": { origin: "Aliment", def: "Mélasse ou sirop de raisin (dibs) consommé par les compagnons au Sham." },
    	    "kinda": { origin: "Tribu", def: "Puissante tribu yéménite dont Al-Ache'ath était un chef." },
    	    "siffine": { origin: "Bataille (37 H)", def: "Affrontement majeur entre Ali et Mouawiya. Al-Ache'ath y commandait l'aile droite d'Ali." },
    	    "lakhmite": { origin: "Tribu", def: "Tribu arabe (Qahtanite) dont était issu Hatib ibn Abou Baltaa." },
    	    "mouqawqis": { origin: "Titre", def: "Patriarche et gouverneur d'Égypte (Coptes) à qui Hatib fut envoyé comme émissaire." },
    	    "sargh": { origin: "Lieu", def: "Village au nord de la péninsule arabique (frontière du Sham) où Oumar décida de ne pas entrer en Syrie à cause de la peste." },
    	    "katam": { origin: "Botanique", def: "Plante utilisée avec le henné pour teindre les cheveux, utilisée par Abou Oubayda." },
    	    "mazdeen": { origin: "Religion", def: "Adeptes du mazdéisme (Zoroastrisme). Abderrahman ibn 'Aouf témoigna que le Prophète avait prélevé la Jizya sur eux." },
    	    "hajar": { origin: "Lieu", def: "Région du Bahreïn antique connue pour sa population mazdéenne." },
    	    "bayt al-mal": { origin: "Institution", def: "Le Trésor public musulman. Abou Oubayda en fut le responsable sous Abou Bakr." },
    	    "banou taim": { origin: "Tribu", def: "Clan de Quraysh auquel appartenait Talha ibn Oubayd-Allah." },
    	    "al-joumay": { origin: "Lieu", def: "Endroit près de Médine (Al-Ghaba/La Forêt) où Zoubayr avait des terres." },
    	    "al-aqiq": { origin: "Lieu", def: "Vallée fertile près de Médine où Saad et Saïd avaient leurs demeures et sont décédés." },
    	    "jalula": { origin: "Bataille (19 H)", def: "Victoire majeure dirigée par Saad contre les Perses, surnommée « la Victoire des Victoires »." },
    	    "qatane": { origin: "Expédition", def: "Montagne/Oasis où Abou Salama mena une expédition (150 hommes) avant de mourir." },
    	    "terfesse": { origin: "Aliment", def: "Champignon (truffe du désert) dont le suc est un remède pour les yeux, selon un hadith rapporté par Saïd." },
    	    "hanifiya": { origin: "Croyance", def: "Le monothéisme pur d'Ibrahim. Zayd ibn Amr (père de Saïd) mourut sur cette voie avant l'Islam." },
    	    "rabigh": { origin: "Lieu", def: "Lieu de la première escarmouche de l'Islam où Saad tira la première flèche." },
    	    "mouharram": { origin: "Calendrier", def: "Premier mois du calendrier islamique." },
    	    "ar-raji": { origin: "Lieu", def: "Lieu situé entre La Mecque et Ousfane, théâtre d'une expédition tragique en l'an 4 H où Khalid ibn Al-Boukayr fut tué." },
            "ousfane": { origin: "Lieu", def: "Contrée située à environ 80 km au nord-ouest de La Mecque." },
            "al-abwa": { origin: "Lieu", def: "Village entre Médine et La Mecque où mourut Abd-Allah ibn Abd-Allah (et où est enterrée la mère du Prophète)." },
            "rafidite": { origin: "Secte", def: "Terme désignant certains groupes chiites extrêmes, utilisé ici concernant la calomnie d'Aïsha." },
            "satrape": { origin: "Titre", def: "Gouverneur de province dans l'ancien empire perse. Al-Bara en tua un en duel." },
            "az-zarah": { origin: "Lieu", def: "Ville côtière historique de l'est de la péninsule arabique (actuelle Qatif)." },
            "simoun": { origin: "Météo", def: "Vent de désert très chaud et violent qui causa la mort d'Abd-Allah ibn Abd-Allah." },
            "baba": { origin: "Surnom", def: "Surnom affectueux donné aux nourrissons bien portants, attribué à Abd-Allah ibn Al-Harith par sa tante Hind." },
	        "al-ashraf": { origin: "Personnage", def: "Poète et chef tribal hostile à l'Islam. Ses satires contre le Prophète entraînèrent son exécution par un groupe d'Ansar (dont Abou 'Abs)." },
	        "banu mustaliq": { origin: "Tribu", def: "Branche de la tribu de Khuza'a. Après leur défaite (5 H), le mariage du Prophète avec Juwayriya entraîna l'affranchissement de toute la tribu." },
	        "adilla": { origin: "Oussoul", def: "Pluriel de Dalil. Ce sont les preuves et sources de la Loi (Coran, Sunna, Consensus, Analogie)." },
    	    "istidlal": { origin: "Oussoul", def: "Méthode de déduction. L'acte d'extraire une règle juridique à partir d'une preuve." },
    	    "al-asl": { origin: "Oussoul", def: "Le Fondement ou l'Origine. Désigne ici les sources primaires : le Coran et la Sunna." },
   	        "ma'qul al-asl": { origin: "Oussoul", def: "Ce qui est raisonné à partir du texte (l'esprit de la loi), comme l'analogie (Qiyas) ou le sens implicite." },
   	        "istishab": { origin: "Oussoul", def: "Principe de continuité : une chose reste dans son état initial (licite ou illicite) tant qu'une preuve ne vient pas la changer." },
    	    "majaz": { origin: "Langue", def: "Sens figuré ou métaphorique d'un mot, par opposition à sa vérité littérale (Haqiqa)." },
    	    "ijma": { origin: "Source", def: "Consensus des savants musulmans sur une question juridique après la mort du Prophète." },
            "mantuq": { origin: "Oussoul", def: "Le Prononcé. Ce que le mot ou l'expression indique explicitement dans le texte (ex: 'Honore les étudiants')." },
            "mafhum": { origin: "Oussoul", def: "Le Compris. Sens juridique déduit du texte sans être explicitement prononcé." },
            "mafhum al-muwafaqa": { origin: "Oussoul", def: "Compréhension par concordance. Lorsque le jugement de l'implicite concorde avec celui du prononcé (l'interdit rappelle un autre interdit)." },
            "fahwa al-khitab": { origin: "Oussoul", def: "Type de concordance où l'implicite est plus fort que le prononcé (a fortiori). Ex: Si dire 'Ouf' est interdit, frapper l'est encore plus." },
            "lahn al-khitab": { origin: "Oussoul", def: "Type de concordance où l'implicite est égal au prononcé. Ex: Brûler les biens de l'orphelin équivaut à les manger (destruction)." },
            "mafhum al-mukhalafa": { origin: "Oussoul", def: "Compréhension par divergence (a contrario). Lorsque le jugement implicite est l'inverse du jugement prononcé." },
            "dalil al-khitab": { origin: "Oussoul", def: "Autre nom pour Mafhum al-Mukhalafa (Preuve du discours)." },
            "mafhum al-'adad": { origin: "Oussoul", def: "Concept du nombre. Débat sur la valeur restrictive d'un chiffre cité dans un texte (ex: 80 coups de fouet). Est-ce une limite infranchissable ou une indication ?" },
            "saliqa": { origin: "Langue", def: "Instinct linguistique ou nature. La faculté innée des Compagnons à comprendre la langue et les subtilités du texte sans avoir besoin de règles grammaticales codifiées." },
            "mutakallimin": { origin: "École", def: "Méthode des Théologiens (majorité : Shafi'ites, Malikites, Hanbalites). Approche qui établit les règles théoriques (Oussoul) indépendamment des cas pratiques (Furu')." },
            "fuqaha": { origin: "École", def: "Méthode des Juristes (Hanafites). Approche qui extrait et codifie les règles (Oussoul) à partir des jugements juridiques (Furu') déjà émis par les Imams." },
            "furu'": { origin: "Fiqh", def: "Branches. Désigne les cas pratiques et les jugements juridiques détaillés (ex: règles de la prière), par opposition aux 'Oussoul' (les racines/règles)." },
            "tajrid": { origin: "Méthode", def: "Abstraction. Caractéristique de la méthode des Mutakallimin qui consiste à isoler la règle pure (le concept) sans nécessairement la lier à un exemple pratique." },
            "mazj": { origin: "Méthode", def: "Mélange. Caractéristique de la méthode des Hanafites qui mélange la règle théorique avec l'application pratique." },
            "ta'sis": { origin: "Méthode", def: "Fondation. L'objectif des Mutakallimin est de 'fonder' la règle, même si elle contredit un jugement pratique existant." },
            "taqrir": { origin: "Méthode", def: "Confirmation. L'objectif des Hanafites est de 'confirmer' ou justifier les jugements pratiques de leurs Imams par des règles." },
            "istihsan": { origin: "Oussoul", def: "Préférence Juridique ou Appréciation. Preuve secondaire (acceptée par les Hanafites, rejetée par Al-Shafi'i) consistant à privilégier une solution pour sa commodité ou justice face à une analogie stricte." },
            "istinbat": { origin: "Oussoul", def: "Extraction ou Inférence. L'effort intellectuel permettant de déduire une règle cachée ou un jugement à partir d'un texte sacré." },
            "malika": { origin: "Psychologie", def: "Compétence ancrée ou aptitude mentale. L'Imam Al-Shafi'i a transformé cette aptitude implicite des premiers savants en une science explicite et codifiée." },
            "asbab al-nuzul": { origin: "Coran", def: "Les causes de la révélation. Contexte historique spécifique ayant déclenché la révélation d'un verset, connu naturellement par les Compagnons présents." },
            "naskh": { origin: "Oussoul", def: "L'Abrogation. Concept codifié par Al-Shafi'i désignant l'annulation d'un jugement antérieur par un texte révélé ultérieurement." },
            "isnad": { origin: "Hadith", def: "Chaîne de transmission. Liste des rapporteurs d'un hadith, inutile pour les Compagnons qui entendaient directement le Prophète." },
            "man": { origin: "Langue", def: "Particule 'Qui'. Désigne instinctivement pour les Arabes les êtres doués de raison (Al-'Aqil)." },
            "ma": { origin: "Langue", def: "Particule 'Quoi/Ce que'. Désigne instinctivement pour les Arabes les choses non douées de raison (Ghayr al-'Aqil)." },
            "al-mantuq": { origin: "Oussoul", def: "Le Prononcé. Ce que le mot indique explicitement dans le texte (ex: 'Honore les étudiants')." },
            "al-mafhum": { origin: "Oussoul", def: "Le Compris. Ce qui est déduit du texte sans être explicitement prononcé (l'esprit du texte)." },
            "mukallaf": { origin: "Fiqh", def: "Le Responsable légal. Personne pubère et saine d'esprit dont les actes sont jugés par la Loi (halal, haram, etc.)." },
            "dalil ijmali": { origin: "Oussoul", def: "Preuve Globale. Règle générale qui ne concerne pas un sujet unique mais s'applique universellement (ex: 'L'ordre implique l'obligation'). C'est l'outil principal de l'Oussouli." },
            "dalil tafsili": { origin: "Oussoul", def: "Preuve Détaillée. Texte spécifique (verset ou hadith) concernant un cas précis (ex: verset sur la prière). C'est la matière première du Faqih." },
            "ma'lum min al-din bid-darura": { origin: "Fiqh", def: "Connu de la religion par nécessité. Vérités évidentes que tout musulman connaît (ex: obligation des 5 prières, interdiction de l'adultère). Leur connaissance n'est pas considérée comme du 'Fiqh' spéculatif." },
            "zann": { origin: "Oussoul", def: "Speculation ou Opinion prépondérante. Niveau de connaissance suffisant pour les actes pratiques (Fiqh) mais insuffisant pour les croyances dogmatiques (Aqida) qui exigent la certitude." },
            "qa'ida mustamirra": { origin: "Oussoul", def: "Règle constante. Une des définitions du mot 'Asl' : un principe qui s'applique de manière continue sans interruption." },
            "qiyas mantiqi": { origin: "Logique", def: "Syllogisme logique. Structure de raisonnement composée d'une mineure (texte) et d'une majeure (règle oussouli) pour produire une conclusion (jugement)." },
            "ta'arud": { origin: "Oussoul", def: "Conflit ou Contradiction apparente entre deux preuves. La science des Oussoul offre des méthodes (comme la spécification) pour résoudre ces conflits." },
            "mutafayhiqun": { origin: "Critique", def: "Les prétentieux ou pseudo-savants. Ceux qui prétendent au savoir et à l'Ijtihad sans en posséder les outils ni la méthodologie rigoureuse." },
            "al-fiqh": { origin: "Fiqh", def: "La Compréhension profonde. Techniquement : la connaissance des jugements légaux pratiques acquise par l'effort de réflexion (Ijtihad), par opposition à la simple connaissance des évidences." },
            "ahkam shar'iyya": { origin: "Fiqh", def: "Les Jugements Légaux. Ils se divisent en deux : ceux connus par nécessité (indiscutables) et ceux soumis à l'interprétation (domaine du Fiqh)." },
            "ijtihad": { origin: "Oussoul", def: "Effort intellectuel intense. Processus par lequel le savant extrait un jugement légal à partir des preuves, là où le sens n'est pas immédiatement évident." },
            "hal al-mustafid": { origin: "Oussoul", def: "L'état du Bénéficiaire. Désigne le Mujtahid (le savant qualifié) qui 'bénéficie' des preuves en les extrayant. C'est le troisième pilier de la définition des Oussoul." },
            "zulm": { origin: "Coran", def: "L'Injustice. Dans l'exemple cité sur la méthode d'interprétation, ce terme général dans la sourate Al-An'am a été défini spécifiquement comme le 'Shirk' (Polythéisme) par le Prophète via la sourate Luqman." },
            "halal": { origin: "Fiqh", def: "Licite. Qualifie une action autorisée par le Législateur. C'est l'un des statuts que le Fiqh attribue aux actes du Mukallaf." },
            "haram": { origin: "Fiqh", def: "Illicite/Interdit. Qualifie une action prohibée par le Législateur. L'étude du Fiqh tourne autour de la distinction entre le Halal et le Haram." },
            "dalil": { origin: "Oussoul", def: "La Preuve (Pluriel : Adilla). Linguistiquement : ce qui guide vers quelque chose. Techniquement : la source (comme un verset ou un hadith) sur laquelle s'appuie le Mujtahid pour établir un jugement. L'auteur précise que le terme 'Asl' est souvent utilisé comme synonyme de 'Dalil'." },
            "qiyas": { origin: "Source", def: "L'Analogie. C'est l'une des quatre sources principales de la Loi (avec le Coran, la Sunna et l'Ijma). Elle consiste à lier un cas nouveau à un cas originellement jugé par le texte, en raison d'une cause commune ('Illa)." },
            "dalail ijmaliyya": { origin: "Oussoul", def: "Les Preuves Globales (Pluriel). Désigne l'ensemble des règles universelles et des catégories de preuves (Coran, Sunna, etc.) que l'Oussouli étudie pour fournir au Faqih les outils de déduction. C'est le premier pilier de la définition d'Usul al-Fiqh." },
            "yaqin": { origin: "Epistémologie", def: "La Certitude (100%). Perception ferme et conforme à la réalité, fondée sur une preuve irréfutable. Synonyme de 'Ilm' dans ce contexte." },
"zann": { origin: "Epistémologie", def: "L'Opinion prépondérante (51-99%). Jugement où une possibilité l'emporte sur l'autre sans atteindre la certitude absolue. C'est le domaine d'action du Fiqh." },
"shakk": { origin: "Epistémologie", def: "Le Doute (50%). Équilibre parfait entre deux possibilités sans qu'aucune ne prévale." },
"wahm": { origin: "Epistémologie", def: "L'Illusion (1-49%). La possibilité la plus faible lorsqu'on a deux choix. C'est l'opposé du Zann." },
"jahl بسيط": { origin: "Epistémologie", def: "Ignorance simple. Ne pas savoir et être conscient de son ignorance." },
"jahl murakkab": { origin: "Epistémologie", def: "Ignorance composée. Ne pas savoir mais être convaincu de savoir. C'est croire en une chose contraire à sa réalité." },
"mutawatir": { origin: "Hadith", def: "Information récurrente. Rapportée par un groupe si nombreux qu'il est impossible qu'ils mentent de concert. Il engendre la certitude absolue." },
"ahad": { origin: "Hadith", def: "Information singulière. Tout rapport qui n'atteint pas le degré du Mutawatir. Il engendre le Zann (speculation) mais oblige à l'action pratique." },
"ilm daruri": { origin: "Logique", def: "Savoir nécessaire. Connaissance intuitive qui s'impose à l'esprit sans besoin de réflexion (ex: le chaud et le froid)." },
"ilm nazari": { origin: "Logique", def: "Savoir théorique. Connaissance qui nécessite une réflexion ({Nazar}) et une déduction ({Istidlal}) pour être acquise." },
"nazar": { origin: "Logique", def: "Réflexion. Mouvement de la pensée qui organise des connaissances connues pour aboutir à une inconnue." },
"jahl basit": { origin: "Epistémologie", def: "L'Ignorance Simple. L'état de celui qui ne sait pas et qui est conscient de son ignorance (ex: dire 'je ne sais pas'). Contraire de l'ignorance composée (Jahl Murakkab)." },
"al-shakk": { origin: "Epistémologie", def: "Le Doute (50%). Équilibre parfait entre deux possibilités sans qu'aucune ne prévale sur l'autre (ex: hésiter entre une pierre et un homme au loin)." },
"al-wahm": { origin: "Epistémologie", def: "L'Illusion (1-49%). La possibilité la plus faible (le côté perdant) lorsqu'on a deux choix opposés. C'est l'opposé du Zann." },
"al-zann": { origin: "Epistémologie", def: "L'Opinion Prépondérante (51-99%). Jugement où une possibilité l'emporte sur l'autre sans atteindre la certitude absolue. C'est le niveau requis pour le Fiqh." },
"al-yaqin": { origin: "Epistémologie", def: "La Certitude (100%). Perception ferme, conforme à la réalité et fondée sur une preuve irréfutable, n'acceptant aucun doute." },
"al-'ilm": { origin: "Epistémologie", def: "La Science/Le Savoir. Dans le contexte des niveaux de perception ({Maratib al-Idrak}), ce terme est utilisé comme synonyme exact d'Al-Yaqin (Certitude absolue)." },
"al-mutawatir": { origin: "Hadith", def: "L'Information Récurrente. Rapportée par un groupe si nombreux (à chaque génération) qu'il est impossible qu'ils se soient accordés sur un mensonge. Il engendre la certitude absolue ({Ilm})." },
"al-ahad": { origin: "Hadith", def: "L'Information Singulière. Tout rapport qui n'atteint pas le seuil du Mutawatir (même rapporté par plusieurs personnes). Il engendre le Zann mais oblige à l'action pratique." },
"ghalabat al-zann": { origin: "Epistémologie", def: "La Prépondérance de l'Opinion. Un niveau élevé de Zann qui frôle la certitude et sur lequel le croyant doit baser ses actions (ex: la direction de la Qibla)." },
"hukm shar'i": { origin: "Fiqh", def: "Le Jugement Légal. Discours d'Allah lié aux actes des responsables par demande, choix ou situation." },
"al-hukm al-shar'i": { origin: "Fiqh", def: "Voir Hukm Shar'i." },
"khitab": { origin: "Oussoul", def: "Le Discours. Référence à la Parole d'Allah ({Kalam Nafsi}) qui s'adresse aux humains pour régir leur conduite." },
"al-khitab": { origin: "Oussoul", def: "Voir Khitab." },
"mukallaf": { origin: "Fiqh", def: "Le Responsable. Personne pubère ({Baligh}), saine d'esprit ({'Aqil}) et atteinte par le message, apte à recevoir l'ordre divin." },
"al-mukallaf": { origin: "Fiqh", def: "Voir Mukallaf." },
"iqtida": { origin: "Oussoul", def: "La Demande ou Exigence. Type de discours divin qui réclame une action ou une abstention (couvre le Wajib, Mandub, Haram, Makruh)." },
"al-iqtida": { origin: "Oussoul", def: "Voir Iqtida." },
"takhyir": { origin: "Oussoul", def: "Le Choix. Type de discours divin laissant le responsable libre de faire ou ne pas faire (couvre uniquement le Mubah)." },
"al-takhyir": { origin: "Oussoul", def: "Voir Takhyir." },
"wad'": { origin: "Oussoul", def: "La Situation ou Mise en place. Type de discours où Allah lie un signe naturel ou un acte à un jugement (Causes, Conditions, Empêchements) sans que ce soit un ordre direct de faire." },
"al-wad'": { origin: "Oussoul", def: "Voir Wad'." },
"ijab": { origin: "Oussoul", def: "L'Action d'Obliger. C'est l'attribut du Discours divin (éternel) qui rend une chose obligatoire. À distinguer du 'Wajib' qui est l'acte humain résultant." },
"al-ijab": { origin: "Oussoul", def: "Voir Ijab." },
"wajib": { origin: "Fiqh", def: "L'Obligatoire. L'acte du serviteur dont l'accomplissement est récompensé et le délaissement intentionnel est puni." },
"al-wajib": { origin: "Fiqh", def: "Voir Wajib." },
"nadb": { origin: "Oussoul", def: "L'Appel ou Recommandation. L'attribut du Discours divin incitant à faire sans obligation." },
"al-nadb": { origin: "Oussoul", def: "Voir Nadb." },
"mandub": { origin: "Fiqh", def: "Le Recommandé. L'acte dont l'accomplissement est récompensé mais le délaissement n'est pas puni." },
"al-mandub": { origin: "Fiqh", def: "Voir Mandub." },
"tahrim": { origin: "Oussoul", def: "L'Action d'Interdire. L'attribut du Discours divin rendant une chose prohibée." },
"al-tahrim": { origin: "Oussoul", def: "Voir Tahrim." },
"haram": { origin: "Fiqh", def: "L'Interdit. L'acte dont le délaissement est récompensé et l'accomplissement intentionnel est puni." },
"al-haram": { origin: "Fiqh", def: "Voir Haram." },
"karaha": { origin: "Oussoul", def: "La Détestation. L'attribut du Discours divin demandant de laisser une chose sans fermeté." },
"al-karaha": { origin: "Oussoul", def: "Voir Karaha." },
"makruh": { origin: "Fiqh", def: "Le Détestable. L'acte dont le délaissement est récompensé mais l'accomplissement n'est pas puni." },
"al-makruh": { origin: "Fiqh", def: "Voir Makruh." },
"ibaha": { origin: "Oussoul", def: "L'Action de Permettre. L'attribut du Discours divin donnant le choix." },
"al-ibaha": { origin: "Oussoul", def: "Voir Ibaha." },
"mubah": { origin: "Fiqh", def: "Le Permis. L'acte pour lequel il n'y a ni récompense ni punition intrinsèque." },
"al-mubah": { origin: "Fiqh", def: "Voir Mubah." },
"kalam nafsi": { origin: "Aqida", def: "Parole Psychologique/Éternelle. Attribut d'Allah désignant Sa Parole incréée existant en Lui-même, distincte des sons et lettres créés qui l'expriment." },
"majaz": { origin: "Langue", def: "Métaphore. Utilisation d'un mot au-delà de son sens littéral. Ex: 'L'alcool est interdit' est une métaphore pour 'Boire l'alcool est interdit'." },
"al-majaz": { origin: "Langue", def: "Voir Majaz." },
"sabab": { origin: "Oussoul", def: "La Cause. Signe placé par Allah pour indiquer le début d'un jugement (ex: le coucher du soleil est la cause de l'obligation du Maghreb). Relève du Hukm Wad'i." },
"al-sabab": { origin: "Oussoul", def: "Voir Sabab." },
"hukm wad'i": { origin: "Oussoul", def: "Jugement Situationnel. Discours divin qui établit des signes ({Alamat}) liant les phénomènes juridiques entre eux (Cause, Condition, Empêchement) sans formuler d'ordre direct." },
"al-hukm al-wad'i": { origin: "Oussoul", def: "Voir Hukm Wad'i." },
"hukm taklifi": { origin: "Oussoul", def: "Jugement d'Obligation. Discours divin demandant directement au responsable d'agir ou de s'abstenir." },
"sabab": { origin: "Oussoul", def: "La Cause. Ce dont la présence entraîne la présence du jugement et l'absence entraîne l'absence (Corrélation bidirectionnelle). Ex: Le vol est la cause de l'amputation." },
"al-sabab": { origin: "Oussoul", def: "Voir Sabab." },
"shart": { origin: "Oussoul", def: "La Condition. Ce dont l'absence entraîne l'absence du jugement, mais dont la présence ne suffit pas à elle seule pour que le jugement existe (Corrélation unidirectionnelle par le néant). Ex: Le Wudu pour la prière." },
"al-shart": { origin: "Oussoul", def: "Voir Shart." },
"mani'": { origin: "Oussoul", def: "L'Empêchement. Ce dont la présence empêche le jugement d'exister. Ex: Les menstrues empêchent l'obligation de la prière." },
"al-mani'": { origin: "Oussoul", def: "Voir Mani'." },
"sahih": { origin: "Fiqh", def: "Le Valide/Correct. Acte qui remplit toutes ses conditions et piliers, et produit ses effets juridiques (Nufudh). Opposé de Batil." },
"al-sahih": { origin: "Fiqh", def: "Voir Sahih." },
"batil": { origin: "Fiqh", def: "Le Nul/Invalide. Acte qui ne remplit pas ses conditions et ne produit aucun effet juridique. Synonyme de Fasid pour la majorité (sauf Hanafites)." },
"al-batil": { origin: "Fiqh", def: "Voir Batil." },
"fasid": { origin: "Fiqh", def: "Le Vicié. Synonyme de Batil pour la majorité. Pour les Hanafites (dans les transactions) : acte légal dans son fond mais illégal dans sa description, produisant des effets partiels." },
"al-fasid": { origin: "Fiqh", def: "Voir Fasid." },
"itlaf": { origin: "Fiqh", def: "La Destruction/Dommage. Action de détruire le bien d'autrui. C'est une 'Cause' ({Sabab}) situationnelle qui déclenche l'obligation de rembourser, même pour un enfant." },
"daman": { origin: "Fiqh", def: "La Garantie/Responsabilité financière. Obligation de compenser un dommage causé. Résulte du Hukm Wad'i." },
"fard 'ayn": { origin: "Fiqh", def: "Obligation Individuelle. Devoir exigé de chaque personne spécifiquement (ex: Prière). L'objectif est l'individu." },
"fard kifaya": { origin: "Fiqh", def: "Obligation Communautaire/De Suffisance. Devoir exigé de la communauté globale. Si certains l'accomplissent, les autres en sont déchargés. L'objectif est la réalisation de l'action, peu importe par qui (ex: Prière mortuaire)." },
"i'lam": { origin: "Oussoul", def: "L'Information ou Annonce. Le jugement situationnel ({Wad'i}) est défini comme une information donnée par Allah sur les signes ({Alamat}) qu'Il a placés, contrairement au jugement d'obligation qui est une demande directe." },
"alamat": { origin: "Oussoul", def: "Les Signes (Pluriel de 'Alama). Indicateurs posés par le Législateur (comme le feu rouge dans le code de la route ou le soleil pour la prière) pour signaler le moment d'appliquer un jugement." },
"iskar": { origin: "Fiqh", def: "L'Ivresse/Enivrement. Cité comme exemple de Cause ({Sabab}) : son existence entraîne l'existence de l'Interdiction ({Tahrim}). Si l'ivresse disparaît (vinaigre), l'interdiction disparaît." },
"hayd": { origin: "Fiqh", def: "Les Menstrues. Citées comme exemple d'Empêchement ({Mani'}) : leur présence empêche l'obligation de la prière." },
"qabul": { origin: "Théologie", def: "L'Acceptation Divine. C'est l'agrément d'Allah et la récompense dans l'au-delà. Distinct de la Validité ({Sihha}) : une prière peut être valide juridiquement (remplir les conditions) sans que l'on sache si elle est acceptée par Dieu." },
"mu'amalat": { origin: "Fiqh", def: "Les Transactions. Les relations interhumaines (ventes, contrats). Domaine où les Hanafites distinguent le Nul ({Batil}) du Vicié ({Fasid}), contrairement aux Adorations ({Ibadat})." },
"taklifi": { origin: "Oussoul", def: "Qualificatif du Jugement d'Obligation. Désigne le discours qui s'adresse directement au responsable pour lui demander de faire ou ne pas faire." },
"wad'i": { origin: "Oussoul", def: "Qualificatif du Jugement Situationnel. Désigne le discours qui 'pose' ({Wada'a}) des causes et des conditions. Il s'applique même à ceux qui ne sont pas responsables (comme l'enfant qui doit rembourser ce qu'il casse)." },
"al-kitab": { origin: "Source", def: "Le Livre (Le Coran). Mentionné comme la première des preuves globales ({Adilla Ijmaliyya}) étudiées dans la structure des Oussoul." },
"haqiqa": { origin: "Langue", def: "La Vérité (Sens Propre). Utilisation d'un mot dans le sens pour lequel il a été initialement institué ({Wudi'a lahu}) par les fondateurs de la langue, la Loi ou la coutume." },
"al-haqiqa": { origin: "Langue", def: "Voir Haqiqa." },
"majaz": { origin: "Langue", def: "La Métaphore (Sens Figuré). Utilisation d'un mot hors de son sens originel en raison d'une relation ({'Alaqa}) et avec un indice ({Qarina}) empêchant le sens propre." },
"al-majaz": { origin: "Langue", def: "Voir Majaz." },
"qarina": { origin: "Oussoul", def: "L'Indice Contextuel. Élément (verbal ou circonstanciel) qui accompagne le mot et indique qu'il ne faut pas le comprendre au sens propre (ex: 'un lion *avec une épée*')." },
"al-qarina": { origin: "Oussoul", def: "Voir Qarina." },
"wad'": { origin: "Langue", def: "L'Assignation/Institution. Acte de lier un mot à un sens spécifique (ex: lier le son 'Asad' à l'animal lion). C'est la base de la distinction Haqiqa/Majaz." },
"al-wad'": { origin: "Langue", def: "Voir Wad'." },
"haqiqa lughawiyya": { origin: "Langue", def: "Vérité Linguistique. Le sens du mot selon le dictionnaire originel de la langue (ex: 'Salat' = Invocation)." },
"haqiqa shar'iyya": { origin: "Oussoul", def: "Vérité Légale/Religieuse. Le sens spécifique donné par la Charia à un mot, qui prévaut sur le sens linguistique dans les textes (ex: 'Salat' = Prière rituelle)." },
"haqiqa urfiyya": { origin: "Oussoul", def: "Vérité Coutumière. Le sens donné par l'usage social ou technique à un mot (ex: 'Dabba' = animal à 4 pattes, excluant l'homme)." },
"majaz mursal": { origin: "Béloquence", def: "Métaphore 'Envoyée' (non restreinte par la ressemblance). Relation logique autre que la similitude, comme la cause pour l'effet (ex: 'Pluie' appelée 'Rizq')." },
"majaz 'aqli": { origin: "Béloquence", def: "Métaphore Intellectuelle. Attribution ({Isnad}) d'une action à celui qui l'a causée plutôt qu'à celui qui l'a faite physiquement (ex: 'Le Prince a bâti la ville')." },
"dabba": { origin: "Langue", def: "La Bête/Ce qui rampe. Linguistiquement : tout être vivant qui se déplace sur terre (incluant l'humain). Coutumièrement : restreint aux animaux de trait." },
"al-dabba": { origin: "Langue", def: "Voir Dabba." },
"salah": { origin: "Fiqh", def: "La Prière. Linguistiquement : Invocation ({Du'a}). Légalement : Rituel composé de paroles et gestes spécifiques. Exemple type de la primauté de la Vérité Légale." },
"al-salah": { origin: "Fiqh", def: "Voir Salah." },
"ziyada": { origin: "Langue", def: "L'Ajout. Type de Majaz où un mot est ajouté pour l'emphase (ex: le 'Ka' dans 'Laysa Kamithlihi shay')." },
"nuqsan": { origin: "Langue", def: "L'Omission. Type de Majaz où un mot est sous-entendu (ex: 'Interroge la ville' pour 'les gens de la ville')." },
// Complément Glossaire Leçon 8

"mabahith al-alfaz": { origin: "Oussoul", def: "Recherches sur les Mots/Expressions. Chapitre fondamental des Oussoul étudiant la relation entre la langue et le sens juridique." },
"al-mantuq": { origin: "Oussoul", def: "Le Prononcé. Sens tiré directement de l'énoncé du mot (ex: 'Faites' indique l'ordre)." },
"al-mafhum": { origin: "Oussoul", def: "Le Compris. Sens déduit qui n'est pas explicitement prononcé (ex: 'Ne leur dis pas Ouf' implique ne pas frapper)." },
"amr": { origin: "Oussoul", def: "L'Ordre/Impératif. Formule demandant la réalisation d'une action (implique généralement l'obligation)." },
"al-amr": { origin: "Oussoul", def: "Voir Amr." },
"nahi": { origin: "Oussoul", def: "L'Interdiction. Formule demandant l'abstention d'une action (implique généralement la prohibition)." },
"al-nahi": { origin: "Oussoul", def: "Voir Nahi." },
"ummum": { origin: "Oussoul", def: "La Généralité. Mot couvrant la totalité de ses unités sans restriction (ex: 'Les hommes')." },
"al-ummum": { origin: "Oussoul", def: "Voir Ummum." },
"khusus": { origin: "Oussoul", def: "La Spécificité. Mot ne désignant qu'une partie ou un individu (ex: 'Zayd')." },
"al-khusus": { origin: "Oussoul", def: "Voir Khusus." },
"mutlaq": { origin: "Oussoul", def: "L'Absolu. Mot désignant une essence sans restriction de qualité (ex: 'un esclave' sans préciser croyant ou non)." },
"al-mutlaq": { origin: "Oussoul", def: "Voir Mutlaq." },
"muqayyad": { origin: "Oussoul", def: "Le Restreint/Qualifié. Mot limité par un adjectif ou une condition (ex: 'un esclave croyant')." },
"al-muqayyad": { origin: "Oussoul", def: "Voir Muqayyad." },
"mujmal": { origin: "Oussoul", def: "L'Ambigu/Global. Mot dont le sens et les détails ne sont pas clairs sans explication externe (ex: 'La Prière' dans le Coran)." },
"al-mujmal": { origin: "Oussoul", def: "Voir Mujmal." },
"mubayyin": { origin: "Oussoul", def: "Le Clarifié/Explicite. Mot dont le sens est clair ou a été expliqué par le Législateur." },
"al-mubayyin": { origin: "Oussoul", def: "Voir Mubayyin." },
"zahir": { origin: "Oussoul", def: "L'Apparent. Sens immédiat qui vient à l'esprit, mais qui accepte une autre interprétation." },
"al-zahir": { origin: "Oussoul", def: "Voir Zahir." },
"mu'awwal": { origin: "Oussoul", def: "L'Interprété. Sens secondaire d'un mot, préféré au sens apparent grâce à une preuve (ex: 'La Main' interprétée comme 'La Puissance')." },
"al-mu'awwal": { origin: "Oussoul", def: "Voir Mu'awwal." },
"nasikh": { origin: "Oussoul", def: "L'Abrogeant. Texte révélé postérieurement qui annule un jugement précédent." },
"al-nasikh": { origin: "Oussoul", def: "Voir Nasikh." },
"mansukh": { origin: "Oussoul", def: "L'Abrogé. Le jugement initial qui a été annulé par le nouveau texte." },
"al-mansukh": { origin: "Oussoul", def: "Voir Mansukh." },
"wudi'a lahu": { origin: "Langue", def: "Ce pour quoi il a été institué. Désigne le sens originel assigné au mot par le fondateur de la langue (critère de la Haqiqa)." },
"asad": { origin: "Langue", def: "Le Lion. Exemple classique : Sens propre ({Haqiqa}) = animal prédateur. Sens figuré ({Majaz}) = homme courageux." },
"al-asad": { origin: "Langue", def: "Voir Asad." },
"far'": { origin: "Oussoul", def: "La Branche/Dérivé. Ici, le Majaz est considéré comme une branche par rapport à la Haqiqa qui est l'origine ({Asl})." },
"al-far'": { origin: "Oussoul", def: "Voir Far'." },
"asl": { origin: "Oussoul", def: "L'Origine/Fondement. Ici, désigne la Haqiqa car elle ne nécessite pas de preuve, contrairement au Majaz." },
"al-asl": { origin: "Oussoul", def: "Voir Asl." },
"wadi'": { origin: "Langue", def: "L'Instituteur. Celui qui 'pose' ou assigne le mot à son sens (Les Arabes, la Loi, ou la Coutume)." },
"al-wadi'": { origin: "Langue", def: "Voir Wadi'." },
"istilah ahl al-fann": { origin: "Méthodologie", def: "Terminologie des spécialistes. Règle stipulant qu'on doit définir un mot selon le dictionnaire de la science concernée (ex: médecine, logique) et non le dictionnaire général." },
"qalb": { origin: "Langue", def: "Le Cœur. Exemple de polysémie technique : muscle en médecine, siège de la foi en religion." },
"al-qalb": { origin: "Langue", def: "Voir Qalb." },
"fa'il": { origin: "Langue", def: "L'Acteur/Sujet. Exemple : En grammaire = celui qui fait l'action. En Aqida = Allah (l'Agent réel)." },
"al-fa'il": { origin: "Langue", def: "Voir Fa'il." },
"rizq": { origin: "Coran", def: "La Subsistance. Exemple de Majaz Mursal : Dans le verset 'Il fait descendre du ciel votre Rizq', le mot Rizq est utilisé pour désigner la Pluie (qui en est la cause)." },
"al-rizq": { origin: "Coran", def: "Voir Rizq." },
"musabbab": { origin: "Logique", def: "L'Effet/Le Causé. Relation utilisée dans le Majaz Mursal où l'on nomme la cause par le nom de l'effet." },
"al-musabbab": { origin: "Logique", def: "Voir Musabbab." },
"isnad": { origin: "Langue", def: "L'Attribution/Imputation. Dans le Majaz 'Aqli, c'est l'action de lier le verbe à un sujet qui n'est pas l'acteur réel (ex: Le Prince a construit)." },
"al-isnad": { origin: "Langue", def: "Voir Isnad." },
"'aql": { origin: "Logique", def: "L'Intellect. Juge qui valide le Majaz 'Aqli en comprenant que l'attribution est figurée et non littérale." },
"al-'aql": { origin: "Logique", def: "Voir 'Aql." },
"mantuq": { origin: "Oussoul", def: "Le Prononcé. Sens tiré directement de l'énoncé du mot et de sa structure linguistique ({Waḍ' Lughawī}). Il s'oppose au Mafhum." },
"al-mantuq": { origin: "Oussoul", def: "Voir Mantuq." },
"mafhum": { origin: "Oussoul", def: "Le Compris. Sens déduit par l'intellect ({'Aql}) à partir de ce qui n'est pas dit dans le texte ({Maskut 'anhu})." },
"al-mafhum": { origin: "Oussoul", def: "Voir Mafhum." },
"nass": { origin: "Oussoul", def: "Le Texte Univoque. Type de Manṭuq qui n'admet qu'un seul sens possible (ex: noms propres, chiffres). Il engendre la Certitude ({Qaṭ'})." },
"al-nass": { origin: "Oussoul", def: "Voir Nass." },
"zahir": { origin: "Oussoul", def: "L'Apparent. Type de Manṭuq qui a un sens prépondérant mais admet une autre probabilité plus faible. Il engendre le Zann." },
"al-zahir": { origin: "Oussoul", def: "Voir Zahir." },
"mujmal": { origin: "Oussoul", def: "L'Ambigu. Type de Manṭuq qui a plusieurs sens possibles à égalité (ex: polysémie totale). Il engendre le Shakk jusqu'à clarification." },
"al-mujmal": { origin: "Oussoul", def: "Voir Mujmal." },
"mafhum al-muwafaqa": { origin: "Oussoul", def: "Concept de Concordance. Sens implicite où le jugement du non-dit est identique ou supérieur à celui du prononcé (a fortiori)." },
"mafhum al-mukhalafa": { origin: "Oussoul", def: "Concept de Divergence. Sens implicite où le jugement du non-dit est l'inverse de celui du prononcé (a contrario)." },
"qullatayn": { origin: "Hadith", def: "Deux Jarres. Mesure de volume d'eau (env. 200L) citée dans un hadith célèbre servant de base à la règle de pureté de l'eau en grande quantité." },
"maskut 'anhu": { origin: "Oussoul", def: "Le Non-Dit/Le Tu. Ce sur quoi le texte a gardé le silence. C'est le domaine d'extraction du Mafhum." },
"qur'": { origin: "Coran", def: "Période menstruelle ou de pureté. Terme polysémique ({Mujmal}) par excellence, signifiant linguistiquement à la fois les règles et la pureté, source de divergence entre les écoles." },
"rajih": { origin: "Logique", def: "Prépondérant. Le sens le plus probable d'un mot (caractéristique du Ẓāhir)." },
"marjuh": { origin: "Logique", def: "Dominé/Faible. Le sens le moins probable d'un mot, qui est délaissé sauf preuve contraire." },
"wad' lughawi": { origin: "Oussoul", def: "Assignation Linguistique. Désigne le sens originel 'posé' par la langue arabe pour un mot, avant tout usage technique ou religieux. Base de la Haqiqa Lughawiya." },
"qat'": { origin: "Oussoul", def: "La Certitude/Le Tranchant. Caractère de ce qui est définitif et ne laisse place à aucune probabilité contraire. S'oppose au Zann (spéculatif)." },
"al-qat'": { origin: "Oussoul", def: "Voir Qat'." },
"tuhr": { origin: "Fiqh", def: "La Pureté. État de pureté rituelle. En droit de la famille, désigne spécifiquement la période de pureté (inter-menstruelle) séparant deux cycles de Hayd." },
"al-tuhr": { origin: "Fiqh", def: "Voir Tuhr." }
        };