(() => {
    const parseRows = window.__parseScholarAtlasRows;
    if (!parseRows || !window.SCHOLAR_ATLAS_DATA) throw new Error('Atlas Savants : base absente avant le lot hadith-tafsir.');
    const rows = `abd-al-razzaq|ʿAbd al-Razzāq al-Ṣanʿānī|عبد الرزاق الصنعاني|126|211|sanaa|sanaa,makkah,madinah|Hadith,Fiqh,Tafsir|Traditionniste|M|Compilateur du Muṣannaf|Un vaste recueil ancien classé par matières, préservant hadiths, avis de compagnons et doctrines de successeurs.|al-Muṣannaf§al-Tafsīr|Établi à Sanaa, il reçut notamment de Maʿmar ibn Rāshid et accueillit des étudiants venus de loin, dont Aḥmad ibn Ḥanbal.|Son Muṣannaf est une source capitale pour l’histoire des pratiques juridiques et des traditions avant les grands recueils canoniques.|al-Dhahabī, Siyar aʿlām al-nubalāʾ§Ibn Ḥajar, Tahdhīb al-tahdhīb
ibn-abi-shayba|Abū Bakr Ibn Abī Shayba|أبو بكر ابن أبي شيبة|159|235|kufa|wasit,kufa,baghdad|Hadith,Fiqh,History|Traditionniste|M|Auteur d’un grand Muṣannaf|Une encyclopédie de traditions classées par thèmes, ainsi qu’un important Musnad.|al-Muṣannaf§al-Musnad|Membre d’une famille de traditionnistes de Koufa, il enseigna à Muslim, Abū Dāwūd et Ibn Mājah.|Son recueil documente les divergences juridiques anciennes et la richesse des matériaux transmis en Irak.|al-Dhahabī, Siyar aʿlām al-nubalāʾ§Ibn Ḥajar, Tahdhīb al-tahdhīb
yahya-main|Yaḥyā ibn Maʿīn|يحيى بن معين|158|233|baghdad|baghdad,kufa,basra,makkah,madinah,sanaa|Hadith,Biography|Critique du hadith|M|Maître de la critique des transmetteurs|Une connaissance exceptionnelle des biographies, des variantes et de la fiabilité des narrateurs.|al-Tārīkh, recensions de ses élèves|Héritier d’une fortune qu’il consacra en grande partie aux voyages et à la collecte, il fut proche d’Aḥmad ibn Ḥanbal et dʿAlī al-Madīnī.|Ses jugements constituent un socle majeur de la science du rijāl et doivent être lus en tenant compte des contextes et des différentes recensions.|al-Khaṭīb al-Baghdādī, Tārīkh Baghdād§al-Dhahabī, Siyar aʿlām al-nubalāʾ
ali-madini|ʿAlī ibn al-Madīnī|علي بن المديني|161|234|basra|basra,baghdad,makkah,madinah|Hadith,Biography|Critique du hadith|M|Spécialiste des défauts subtils du hadith|L’analyse des ʿilal, des réseaux de maîtres et des différences entre voies de transmission.|al-ʿIlal§Maʿrifat al-rijāl, œuvres partiellement conservées|Né à Bassora, il devint l’un des maîtres les plus influents d’al-Bukhārī dans la critique technique du hadith.|Son approche comparative des chaînes a façonné la méthode des grands compilateurs du IIIe siècle.|al-Dhahabī, Siyar aʿlām al-nubalāʾ§Ibn Ḥajar, Tahdhīb al-tahdhīb
ibn-hibban|Muḥammad Ibn Ḥibbān al-Bustī|محمد ابن حبان البستي|270|354|bust|bust,nishapur,rayy,basra,mosul,damascus,cairo|Hadith,Biography,Fiqh|Traditionniste|M|Compilateur et biographe des transmetteurs|Un Ṣaḥīḥ organisé selon une architecture originale et de vastes dictionnaires de narrateurs.|Ṣaḥīḥ Ibn Ḥibbān§al-Thiqāt§al-Majrūḥīn|Originaire de Bust, il voyagea très largement, exerça comme juge et fonda une institution savante dans sa ville.|Son œuvre est précieuse mais sa méthode de qualification des transmetteurs fait aussi l’objet de discussions techniques.|al-Dhahabī, Siyar aʿlām al-nubalāʾ§Ibn Ḥibbān, al-Thiqāt
hakim-nishapuri|al-Ḥākim al-Nīsābūrī|الحاكم النيسابوري|321|405|nishapur|nishapur,baghdad,makkah,madinah|Hadith,Biography,History|Traditionniste|M|Historien et traditionniste de Nishapur|Le Mustadrak et une documentation abondante sur les maîtres, les sciences du hadith et l’histoire locale.|al-Mustadrak§Maʿrifat ʿulūm al-ḥadīth§Tārīkh Naysābūr|Né et établi à Nishapur, il voyagea pour le hadith puis occupa des fonctions judiciaires et enseignantes.|Son Mustadrak est très utilisé, mais les degrés qu’il attribue demandent souvent une réévaluation critique détaillée.|al-Dhahabī, Siyar aʿlām al-nubalāʾ§al-Ḥākim, Maʿrifat ʿulūm al-ḥadīth
khatib-baghdadi|al-Khaṭīb al-Baghdādī|الخطيب البغدادي|392|463|baghdad|baghdad,basra,nishapur,damascus,makkah|Hadith,History,Biography|Shafiite|M|Historien de Bagdad et théoricien de la transmission|Une histoire monumentale de Bagdad et des traités sur l’éthique, les procédures et les métiers du hadith.|Tārīkh Baghdād§al-Kifāya§al-Jāmiʿ li-akhlāq al-rāwī|Voyageur et enseignant, il combina enquête biographique, critique des récits et réflexion sur les normes professionnelles du transmetteur.|Ses ouvrages constituent une bibliothèque méthodologique essentielle pour comprendre la formation du métier de muḥaddith.|al-Khaṭīb, Tārīkh Baghdād§al-Dhahabī, Siyar aʿlām al-nubalāʾ
ibn-salah|Ibn al-Ṣalāḥ al-Shahrazūrī|ابن الصلاح الشهرزوري|577|643|damascus|mosul,baghdad,jerusalem,damascus|Hadith,Fiqh|Shafiite|M|Auteur d’une introduction canonique aux sciences du hadith|La systématisation de la terminologie et des catégories de la critique du hadith.|Muqaddimat Ibn al-Ṣalāḥ§Adab al-muftī wa-l-mustaftī|Formé dans plusieurs centres, il dirigea l’enseignement du hadith à la Dār al-Ḥadīth al-Ashrafiyya de Damas.|Sa Muqaddima devint le point de départ de nombreux résumés, commentaires et poèmes didactiques.|al-Dhahabī, Siyar aʿlām al-nubalāʾ§Ibn al-Ṣalāḥ, al-Muqaddima
mujahid|Mujāhid ibn Jabr|مجاهد بن جبر|21|104|makkah|makkah|Tafsir,Qiraat,Fiqh|École de La Mecque|M|Exégète de la génération des successeurs|Une transmission exégétique rattachée à Ibn ʿAbbās et une attention à la langue et aux circonstances des passages.||Client des Banū Makhzūm, il étudia à La Mecque et fut une référence pour plusieurs exégètes et lecteurs postérieurs.|Les traditions qui lui sont attribuées sont fondamentales, tout en nécessitant l’examen des chaînes et des couches de transmission.|al-Ṭabarī, Jāmiʿ al-bayān§al-Dhahabī, Siyar aʿlām al-nubalāʾ
qatada|Qatāda ibn Diʿāma|قتادة بن دعامة|60|117|basra|basra|Tafsir,Hadith,Arabic|École de Bassora|M|Exégète et mémorisateur de Bassora|Un vaste corpus d’interprétations, de traditions historiques et de remarques linguistiques.||Aveugle dès son jeune âge selon les notices, il développa une mémoire célèbre et transmit dans le grand milieu intellectuel de Bassora.|Son matériel exégétique est largement conservé chez ʿAbd al-Razzāq, al-Ṭabarī et d’autres compilateurs.|al-Ṭabarī, Jāmiʿ al-bayān§al-Dhahabī, Siyar aʿlām al-nubalāʾ`;
    const scholars = parseRows(rows, ['id','name','arabic','born','died','city','routes','disciplines','school','gender','title','knownFor','works','bio','legacy','sources']).map((item) => ({
        ...item,
        born: Number(item.born), died: Number(item.died),
        routes: item.routes ? item.routes.split(',') : [],
        disciplines: item.disciplines ? item.disciplines.split(',') : [],
        works: item.works ? item.works.split('§') : [],
        sources: item.sources ? item.sources.split('§') : []
    }));
    window.SCHOLAR_ATLAS_DATA.scholars.push(...scholars);
})();
