(() => {
    const parseRows = window.__parseScholarAtlasRows;
    if (!parseRows || !window.SCHOLAR_ATLAS_DATA) throw new Error('Atlas Savants : base absente avant le lot sciences-histoire.');
    const rows = `dinawari|Abū Ḥanīfa al-Dīnawarī|أبو حنيفة الدينوري|213|282|isfahan|isfahan,kufa,basra,baghdad|Botany,Astronomy,History,Arabic|Sciences|M|Botaniste et polygraphe|Un traité botanique fondé sur la langue, l’observation et les savoirs agricoles arabes.|Kitāb al-Nabāt§al-Akhbār al-ṭiwāl|Originaire de Dīnawar, il étudia les sciences et la langue en Irak et en Iran.|Son Kitāb al-Nabāt, partiellement conservé, constitue une étape majeure de la botanique descriptive en arabe.|Ibn al-Nadīm, al-Fihrist§al-Dīnawarī, fragments du Kitāb al-Nabāt
razi-physician|Abū Bakr al-Rāzī|أبو بكر الرازي|251|313|rayy|rayy,baghdad|Medicine,Chemistry,Philosophy|Sciences médicales|M|Clinicien et auteur médical|Une médecine clinique attentive à l’observation, au diagnostic différentiel et à la compilation critique des expériences.|al-Ḥāwī§al-Manṣūrī§Kitāb al-Judarī wa-l-ḥaṣba|Né à Rayy, il dirigea des hôpitaux à Rayy et à Bagdad et rédigea une œuvre médicale considérable.|Ses descriptions de la variole et de la rougeole, ainsi que son approche clinique, eurent une longue réception en arabe et en latin.|Ibn Abī Uṣaybiʿa, ʿUyūn al-anbāʾ§al-Rāzī, al-Ḥāwī
ibn-nafis|ʿAlāʾ al-Dīn Ibn al-Nafīs|علاء الدين ابن النفيس|607|687|cairo|damascus,cairo|Medicine,Anatomy,Fiqh|Shafiite / Médecine|M|Médecin et commentateur anatomique|Une description célèbre de la circulation pulmonaire dans sa critique de l’anatomie galénique.|Sharḥ Tashrīḥ al-Qānūn§al-Mūjaz fī al-ṭibb§al-Shāmil fī al-ṣināʿa al-ṭibbiyya|Formé à Damas, il exerça et enseigna au Caire tout en étudiant le droit shafiite.|Son œuvre montre comment le commentaire pouvait devenir un lieu de correction scientifique et d’innovation anatomique.|Ibn Abī Uṣaybiʿa, ʿUyūn al-anbāʾ§Ibn al-Nafīs, Sharḥ Tashrīḥ al-Qānūn
jazari-engineer|Badīʿ al-Zamān al-Jazarī|بديع الزمان الجزري|548|602|diyarbakir|diyarbakir|Engineering,Mechanics,Hydraulics|Sciences|M|Ingénieur des automates et de l’hydraulique|Des machines à eau, horloges, automates et dispositifs mécaniques décrits avec précision.|al-Jāmiʿ bayna al-ʿilm wa-l-ʿamal al-nāfiʿ fī ṣināʿat al-ḥiyal|Il travailla au service des Artuqides à Āmid et documenta des décennies de pratique d’ingénierie.|Son traité relie dessin, fabrication, expérimentation et maintenance, offrant une source exceptionnelle sur la technologie médiévale.|al-Jazarī, al-Jāmiʿ§Ibn Abī Uṣaybiʿa, notices sur les médecins et ingénieurs
jamshid-kashi|Jamshīd al-Kāshī|جمشيد الكاشي|790|832|samarqand|kashan,herat,samarqand|Mathematics,Astronomy|Observatoire de Samarcande|M|Mathématicien et calculateur de haute précision|Des méthodes décimales, des approximations remarquables et des instruments théoriques pour l’astronomie.|Miftāḥ al-ḥisāb§al-Risāla al-muḥīṭiyya§Zīj al-Khāqānī|Originaire de Kashan, il rejoignit le cercle d’Ulugh Beg à Samarcande et participa à son programme scientifique.|Sa précision numérique, notamment dans le calcul de π et des tables trigonométriques, marque un sommet des mathématiques médiévales.|al-Kāshī, Miftāḥ al-ḥisāb§Lettres d’al-Kāshī depuis Samarcande
ulugh-beg|Ulugh Beg|أولوغ بيك|796|853|samarqand|herat,samarqand|Astronomy,Mathematics,Patronage|Observatoire de Samarcande|M|Prince-astronome et mécène|Un observatoire monumental, une madrasa et des tables astronomiques d’une grande précision.|Zīj-i Jadīd-i Gūragānī|Petit-fils de Tamerlan, il gouverna Samarcande tout en rassemblant des mathématiciens et astronomes de premier plan.|Son programme montre le rôle du patronage, des instruments collectifs et des observations répétées dans la production scientifique.|Zīj-i Gūragānī§Chroniques timourides sur Samarcande
farghani|Aḥmad al-Farghānī|أحمد الفرغاني|180|247|baghdad|ferghana,baghdad,cairo|Astronomy,Engineering,Geography|Sciences abbassides|M|Astronome de la tradition abbasside|Une synthèse accessible de l’astronomie ptoléméenne et des travaux d’ingénierie liés au Nil.|Jawāmiʿ ʿilm al-nujūm|Originaire de Ferghana, il travailla dans les milieux scientifiques abbassides et participa à des projets en Égypte.|Son manuel fut traduit en latin et contribua durablement à la transmission de l’astronomie mathématique.|Ibn al-Nadīm, al-Fihrist§al-Farghānī, Jawāmiʿ ʿilm al-nujūm
battani|Muḥammad al-Battānī|محمد البتاني|240|317|raqqa|harran,raqqa,baghdad|Astronomy,Mathematics|Sciences|M|Astronome d’al-Raqqa|Des observations prolongées, des paramètres astronomiques affinés et un usage avancé de la trigonométrie.|al-Zīj al-Ṣābiʾ|Actif principalement à Raqqa, il conduisit des observations sur plusieurs décennies avant de présenter ses résultats dans un zīj.|Ses mesures du Soleil, de l’année et de la précession influencèrent des astronomes musulmans et européens.|Ibn al-Nadīm, al-Fihrist§al-Battānī, al-Zīj al-Ṣābiʾ
masudi|Abū al-Ḥasan al-Masʿūdī|أبو الحسن المسعودي|283|345|cairo|baghdad,rayy,india,damascus,cairo|History,Geography,Adab|Historien voyageur|M|Historien et géographe du monde islamique|Une histoire universelle nourrie de voyages, d’entretiens et de descriptions des peuples et des milieux.|Murūj al-dhahab§al-Tanbīh wa-l-ishrāf|Originaire de Bagdad, il parcourut l’Iran, l’océan Indien, le Levant et l’Égypte avant de terminer sa vie au Caire.|Son écriture associe histoire politique, géographie humaine, religions et curiosité ethnographique, tout en reflétant les limites de ses sources.|al-Masʿūdī, Murūj al-dhahab§al-Masʿūdī, al-Tanbīh wa-l-ishrāf
ibn-asakir|ʿAlī Ibn ʿAsākir|علي ابن عساكر|499|571|damascus|damascus,baghdad,makkah,madinah,nishapur|Hadith,History,Biography|Shafiite|M|Historien monumental de Damas|Une histoire biographique de Damas qui rassemble chaînes, notices et mémoire urbaine.|Tārīkh Madīnat Dimashq§Tabyīn kadhib al-muftarī|Né dans une famille savante, il entreprit une longue rihla puis revint enseigner dans sa ville.|Son ouvrage est une archive immense des personnes, lieux et traditions du Levant médiéval et une source centrale pour l’histoire de l’asharisme.|Ibn ʿAsākir, Tārīkh Madīnat Dimashq§al-Dhahabī, Siyar aʿlām al-nubalāʾ`;
    const scholars = parseRows(rows, ['id','name','arabic','born','died','city','routes','disciplines','school','gender','title','knownFor','works','bio','legacy','sources']).map((item) => ({
        ...item,
        born: Number(item.born), died: Number(item.died),
        routes: item.routes ? item.routes.split(',') : [],
        disciplines: item.disciplines ? item.disciplines.split(',') : [],
        works: item.works ? item.works.split('§') : [],
        sources: item.sources ? item.sources.split('§') : []
    }));
    window.SCHOLAR_ATLAS_DATA.scholars.push(...scholars);
})();
