(() => {
    const parseRows = window.__parseScholarAtlasRows;
    const rows = `tabari|Muḥammad ibn Jarīr al-Ṭabarī|محمد بن جرير الطبري|224|310|baghdad|rayy,baghdad,basra,kufa,cairo|Tafsir,History,Fiqh|Indépendant|M|Exégète et historien de Bagdad|Un commentaire coranique et une histoire universelle monumentaux.|Jāmiʿ al-bayān§Tārīkh al-rusul wa-l-mulūk|Originaire du Tabaristan, il voyagea puis s’établit à Bagdad.|Son tafsīr conserve une masse exceptionnelle de traditions exégétiques anciennes.|al-Khaṭīb al-Baghdādī, Tārīkh Baghdād§al-Dhahabī, Siyar aʿlām al-nubalāʾ
ashari|Abū al-Ḥasan al-Ashʿarī|أبو الحسن الأشعري|260|324|baghdad|basra,baghdad|Theology|Asharite|M|Théologien sunnite|Une école cherchant à articuler textes révélés et argumentation rationnelle.|al-Ibāna§Maqālāt al-islāmiyyīn|Né à Bassora et actif ensuite à Bagdad.|L’asharisme devint l’une des principales écoles de kalām sunnite.|Ibn ʿAsākir, Tabyīn kadhib al-muftarī§al-Ashʿarī, Maqālāt al-islāmiyyīn
maturidi|Abū Manṣūr al-Māturīdī|أبو منصور الماتريدي|238|333|samarqand|samarqand|Theology,Tafsir|Maturidite|M|Théologien de Samarcande|Une tradition théologique liée au milieu hanafite de Transoxiane.|Kitāb al-tawḥīd§Taʾwīlāt ahl al-sunna|Savants de Samarcande dont l’œuvre articule exégèse et raisonnement.|Le maturidisme devint une école majeure de théologie sunnite.|al-Māturīdī, Kitāb al-tawḥīd§al-Samʿānī, al-Ansāb
baqillani|Abū Bakr al-Bāqillānī|أبو بكر الباقلاني|338|403|baghdad|basra,baghdad|Theology,Usul|Asharite|M|Théologien et juriste|La consolidation de l’argumentation asharite et des fondements du droit.|al-Tamhīd§Iʿjāz al-Qurʾān|Théologien malikite actif à Bagdad, connu pour ses débats.|Il joua un rôle central dans la maturation de l’asharisme classique.|Qāḍī ʿIyāḍ, Tartīb al-madārik§Ibn ʿAsākir, Tabyīn kadhib al-muftarī
juwayni|Imām al-Ḥaramayn al-Juwaynī|إمام الحرمين الجويني|419|478|nishapur|nishapur,makkah,madinah|Theology,Usul,Fiqh|Shafiite / Asharite|M|Maître de Nishapur|Des synthèses exigeantes en théologie et en fondements du droit.|al-Burhān§al-Irshād§Nihāyat al-maṭlab|Juriste et théologien appelé Imām al-Ḥaramayn après un séjour au Hedjaz.|Son enseignement influença profondément al-Ghazālī.|al-Subkī, Ṭabaqāt al-shāfiʿiyya§al-Dhahabī, Siyar aʿlām al-nubalāʾ
ghazali|Abū Ḥāmid al-Ghazālī|أبو حامد الغزالي|450|505|tus|tus,nishapur,baghdad,damascus,makkah|Theology,Usul,Fiqh,Spiritualité|Shafiite / Asharite|M|Théologien, juriste et penseur spirituel|Une synthèse de droit, théologie, éthique et spiritualité.|Iḥyāʾ ʿulūm al-dīn§al-Mustaṣfā§Tahāfut al-falāsifa|Formé à Nishapur, professeur à Bagdad, puis voyageur et enseignant.|Son œuvre compte parmi les plus influentes de l’histoire intellectuelle islamique.|al-Subkī, Ṭabaqāt al-shāfiʿiyya§al-Ghazālī, al-Munqidh min al-ḍalāl
razi|Fakhr al-Dīn al-Rāzī|فخر الدين الرازي|544|606|rayy|rayy,khwarazm,bukhara,samarqand,herat|Tafsir,Theology,Philosophy|Shafiite / Asharite|M|Exégète et théologien|Un tafsīr encyclopédique et une argumentation philosophique dense.|Mafātīḥ al-ghayb§al-Maḥṣūl|Originaire de Rayy, il voyagea et enseigna en Orient.|Son œuvre représente un sommet de l’exégèse théologique et rationnelle.|Ibn Khallikān, Wafayāt al-aʿyān§al-Subkī, Ṭabaqāt al-shāfiʿiyya
ibn-taymiyya|Taqī al-Dīn Ibn Taymiyya|تقي الدين ابن تيمية|661|728|damascus|harran,damascus,cairo|Fiqh,Theology,Tafsir|Hanbalite|M|Juriste et théologien de Damas|Une œuvre vaste de critique doctrinale, de droit et d’exégèse.|Darʾ taʿāruḍ al-ʿaql wa-l-naql§Minhāj al-sunna§Majmūʿ al-fatāwā|Né à Harran et réfugié à Damas avec sa famille.|Son influence fut importante dans les débats théologiques et juridiques ultérieurs.|Ibn ʿAbd al-Hādī, al-ʿUqūd al-durriyya§al-Dhahabī, al-Muʿjam al-mukhtaṣṣ
ibn-qayyim|Ibn Qayyim al-Jawziyya|ابن قيم الجوزية|691|751|damascus|damascus,makkah|Fiqh,Spiritualité,Theology|Hanbalite|M|Juriste et auteur spirituel|Des ouvrages sur l’éthique, la spiritualité, le droit et la sīra.|Madārij al-sālikīn§Iʿlām al-muwaqqiʿīn§Zād al-maʿād|Savants damascène et élève d’Ibn Taymiyya.|Son style pédagogique assura une large diffusion à son œuvre.|Ibn Rajab, Dhayl Ṭabaqāt al-ḥanābila§Ibn Kathīr, al-Bidāya wa-l-nihāya
zamakhshari|Maḥmūd al-Zamakhsharī|محمود الزمخشري|467|538|khwarazm|khwarazm,bukhara,baghdad,makkah|Tafsir,Arabic|Muʿtazilite|M|Exégète et linguiste|al-Kashshāf, célèbre pour son analyse linguistique et rhétorique.|al-Kashshāf§Asās al-balāgha|Linguiste de Khwarazm ayant longuement séjourné à La Mecque.|Son tafsīr influença l’étude de la langue du Coran malgré des réserves doctrinales.|Ibn Khallikān, Wafayāt al-aʿyān§al-Suyūṭī, Bughyat al-wuʿāt
qurtubi|Muḥammad al-Qurṭubī|محمد القرطبي|600|671|cairo|cordoba,cairo|Tafsir,Fiqh|Malikite|M|Exégète malikite|Un commentaire attentif aux dimensions juridiques et éthiques du Coran.|al-Jāmiʿ li-aḥkām al-Qurʾān|Originaire de Cordoue, il s’établit en Égypte.|Son tafsīr reste une référence majeure dans la tradition sunnite.|al-Dhahabī, Tārīkh al-islām§al-Qurṭubī, al-Jāmiʿ
ibn-kathir|Ismāʿīl Ibn Kathīr|إسماعيل ابن كثير|701|774|damascus|bosra,damascus|Tafsir,History,Hadith|Shafiite|M|Exégète et historien de Damas|Un tafsīr par les traditions et une vaste histoire universelle.|Tafsīr al-Qurʾān al-ʿaẓīm§al-Bidāya wa-l-nihāya|Formé dans le milieu savant damascène du VIIIe siècle.|Ses ouvrages connurent une diffusion considérable.|Ibn Ḥajar, al-Durar al-kāmina§Ibn Kathīr, al-Bidāya wa-l-nihāya
suyuti|Jalāl al-Dīn al-Suyūṭī|جلال الدين السيوطي|849|911|cairo|cairo,makkah,damascus|Tafsir,Hadith,Arabic,History|Shafiite|M|Polygraphe du Caire|Une production encyclopédique dans de nombreuses sciences.|al-Itqān§al-Durr al-manthūr§Tadrīb al-rāwī§Tārīkh al-khulafāʾ|Savants égyptien connu pour l’ampleur exceptionnelle de sa production.|Ses manuels demeurent très utilisés dans les cursus traditionnels.|al-Suyūṭī, Ḥusn al-muḥāḍara§al-Suyūṭī, al-Taḥadduth bi-niʿmat Allāh
khalil|al-Khalīl ibn Aḥmad|الخليل بن أحمد|100|175|basra|basra|Arabic,Poetics|École de Bassora|M|Linguiste et théoricien de la métrique|Le Kitāb al-ʿAyn et la systématisation de la prosodie arabe.|Kitāb al-ʿAyn|Maître de Bassora, enseignant de Sībawayh et figure fondatrice de la langue.|Ses méthodes structurèrent la lexicographie et l’étude de la poésie.|al-Suyūṭī, Bughyat al-wuʿāt§Ibn al-Nadīm, al-Fihrist
sibawayh|Sībawayh|سيبويه|140|180|basra|isfahan,basra,baghdad|Arabic|École de Bassora|M|Auteur du Kitāb|La première grande synthèse systématique de la grammaire arabe.|al-Kitāb|Originaire de Perse et formé à Bassora auprès d’al-Khalīl.|Son Kitāb devint la référence fondatrice de la grammaire arabe classique.|al-Suyūṭī, Bughyat al-wuʿāt§Ibn al-Nadīm, al-Fihrist
farra|Yaḥyā al-Farrāʾ|يحيى الفراء|144|207|kufa|kufa,baghdad|Arabic,Tafsir|École de Koufa|M|Grammairien de Koufa|Maʿānī al-Qurʾān et l’école grammaticale kufienne.|Maʿānī al-Qurʾān|Linguiste de Koufa actif à Bagdad, spécialiste de la langue du Coran.|Il représente l’un des grands pôles de la grammaire ancienne.|al-Suyūṭī, Bughyat al-wuʿāt§Ibn al-Nadīm, al-Fihrist
jahiz|al-Jāḥiẓ|الجاحظ|160|255|basra|basra,baghdad|Adab,Theology|Muʿtazilite|M|Prosateur et observateur de la société|Une prose inventive sur la langue, les animaux et la culture.|Kitāb al-Ḥayawān§al-Bayān wa-l-tabyīn§al-Bukhalāʾ|Auteur de Bassora actif dans le monde littéraire abbasside.|Il est une figure majeure de l’adab et de la prose arabe.|Ibn al-Nadīm, al-Fihrist§Yāqūt, Muʿjam al-udabāʾ
ibn-jinni|Ibn Jinnī|ابن جني|322|392|mosul|mosul,baghdad,aleppo|Arabic|École de Bagdad|M|Théoricien de la langue|Des analyses profondes de phonologie, morphologie et théorie linguistique.|al-Khaṣāʾiṣ§Sirr ṣināʿat al-iʿrāb|Linguiste né à Mossoul, proche d’Abū ʿAlī al-Fārisī.|Son œuvre demeure fondamentale pour la pensée linguistique arabe.|al-Suyūṭī, Bughyat al-wuʿāt§Yāqūt, Muʿjam al-udabāʾ
ibn-manzur|Ibn Manẓūr|ابن منظور|630|711|cairo|tunis,cairo|Arabic,Adab|Lexicographie|M|Auteur du Lisān al-ʿArab|L’un des dictionnaires les plus vastes de la langue arabe classique.|Lisān al-ʿArab|Lettré d’origine nord-africaine, actif au Caire.|Son dictionnaire est devenu un instrument incontournable pour l’étude des textes.|al-Ṣafadī, al-Wāfī bi-l-wafayāt§Ibn Manẓūr, Lisān al-ʿArab
khwarizmi|Muḥammad al-Khwārizmī|محمد الخوارزمي|164|232|baghdad|khwarazm,baghdad|Mathematics,Astronomy,Geography|Sciences|M|Mathématicien de la Maison de la sagesse|L’algèbre, les méthodes de calcul et des travaux géographiques.|al-Jabr wa-l-muqābala§Zīj al-Sindhind|Savants d’origine khwarazmienne actif à Bagdad sous les Abbassides.|Son nom est à l’origine du mot « algorithme » et son œuvre marqua l’algèbre.|Ibn al-Nadīm, al-Fihrist§al-Khwārizmī, al-Jabr
kindi|Yaʿqūb al-Kindī|يعقوب الكندي|185|256|baghdad|kufa,baghdad|Philosophy,Mathematics,Medicine|Sciences|M|Philosophe arabe|L’adaptation de savoirs philosophiques et scientifiques en langue arabe.|Épîtres philosophiques et scientifiques|Penseur abbasside actif dans les milieux de traduction et de cour.|Il est souvent présenté comme le premier grand philosophe de langue arabe.|Ibn al-Nadīm, al-Fihrist§Ibn Abī Uṣaybiʿa, ʿUyūn al-anbāʾ
biruni|Abū Rayḥān al-Bīrūnī|أبو الريحان البيروني|362|440|ghazni|khwarazm,rayy,ghazni,india|Astronomy,Mathematics,Geography,History|Sciences|M|Astronome et observateur des cultures|Des mesures, des chronologies et une étude remarquable de l’Inde.|al-Qānūn al-Masʿūdī§Taḥqīq mā li-l-Hind§al-Āthār al-bāqiya|Originaire de Khwarazm, il travailla à Ghazni et observa l’Inde.|Sa précision méthodologique en fait une figure majeure de l’histoire des sciences.|al-Bīrūnī, Taḥqīq mā li-l-Hind§al-Bayhaqī, Tatimmat Ṣiwān al-ḥikma
ibn-sina|Ibn Sīnā|ابن سينا|370|428|hamadan|bukhara,khwarazm,rayy,hamadan,isfahan|Medicine,Philosophy,Sciences|Philosophie|M|Médecin et philosophe|Le Canon de la médecine et le Livre de la guérison.|al-Qānūn fī al-ṭibb§Kitāb al-Shifāʾ|Né près de Boukhara, il fut médecin, administrateur et philosophe.|Ses œuvres dominèrent durablement l’enseignement de la médecine et de la philosophie.|Ibn Abī Uṣaybiʿa, ʿUyūn al-anbāʾ§Ibn Sīnā, autobiographie transmise par al-Jūzjānī
ibn-haytham|Ibn al-Haytham|ابن الهيثم|354|430|cairo|basra,baghdad,cairo|Optics,Mathematics,Astronomy|Sciences|M|Pionnier de l’optique|Une étude expérimentale de la vision et de la lumière.|Kitāb al-Manāẓir|Originaire de Bassora, il passa une part importante de sa vie au Caire.|Son Livre de l’optique influença les traditions scientifiques islamique et latine.|Ibn Abī Uṣaybiʿa, ʿUyūn al-anbāʾ§Ibn al-Haytham, Kitāb al-Manāẓir
zahrawi|Abū al-Qāsim al-Zahrāwī|أبو القاسم الزهراوي|325|404|cordoba|cordoba|Medicine|Sciences|M|Médecin et chirurgien d’al-Andalus|Une encyclopédie médicale comprenant un traité de chirurgie illustré.|al-Taṣrīf|Médecin de la région de Cordoue à l’époque omeyyade.|Son œuvre chirurgicale fut traduite et enseignée pendant des siècles.|Ibn Abī Uṣaybiʿa, ʿUyūn al-anbāʾ§al-Zahrāwī, al-Taṣrīf
idrisi|Muḥammad al-Idrīsī|محمد الإدريسي|493|560|palermo|ceuta,cordoba,palermo|Geography|Sciences|M|Géographe de la Méditerranée|Une vaste description du monde et une cartographie réalisée à Palerme.|Nuzhat al-mushtāq|Né au Maghreb, formé en al-Andalus et actif à la cour de Sicile.|Son œuvre témoigne des circulations savantes méditerranéennes.|al-Idrīsī, Nuzhat al-mushtāq§al-Ṣafadī, al-Wāfī bi-l-wafayāt
ibn-rushd|Ibn Rushd|ابن رشد|520|595|cordoba|cordoba,marrakesh|Philosophy,Fiqh,Medicine|Malikite|M|Juriste, médecin et philosophe|Des commentaires d’Aristote et une œuvre juridique comparative.|Bidāyat al-mujtahid§Faṣl al-maqāl§al-Kulliyyāt fī al-ṭibb|Né dans une famille de juristes de Cordoue, il fut juge et médecin.|Son œuvre influença la philosophie islamique, juive et latine.|Ibn Abī Uṣaybiʿa, ʿUyūn al-anbāʾ§Ibn Rushd, Bidāyat al-mujtahid
tusi|Naṣīr al-Dīn al-Ṭūsī|نصير الدين الطوسي|597|672|maragha|tus,baghdad,maragha|Astronomy,Mathematics,Philosophy|Sciences|M|Astronome de Maragha|L’observatoire de Maragha et des modèles astronomiques avancés.|Zīj-i Īlkhānī§Tadhkira fī ʿilm al-hayʾa|Savants persan actif dans les sciences, la philosophie et l’administration.|L’école de Maragha renouvela l’astronomie médiévale.|al-Ṭūsī, al-Tadhkira§Ibn al-Fuwaṭī, Majmaʿ al-ādāb
ibn-khaldun|ʿAbd al-Raḥmān Ibn Khaldūn|عبد الرحمن ابن خلدون|732|808|cairo|tunis,granada,ceuta,cairo,damascus|History,Sociology,Fiqh|Malikite|M|Historien et penseur de la société|La Muqaddima et une théorie de la dynamique des sociétés et des États.|al-Muqaddima§Kitāb al-ʿIbar|Né à Tunis, diplomate et enseignant au Maghreb, en al-Andalus puis au Caire.|Sa réflexion sur l’histoire, le pouvoir et l’économie dépasse largement son époque.|Ibn Khaldūn, al-Taʿrīf§Ibn Khaldūn, al-Muqaddima
karima-marwaziyya|Karīma al-Marwaziyya|كريمة المروزية|365|463|makkah|merv,jerusalem,makkah|Hadith|Traditionniste|F|Autorité du Ṣaḥīḥ al-Bukhārī|Une transmission réputée du Ṣaḥīḥ al-Bukhārī à La Mecque.||Originaire de Merv, elle enseigna à La Mecque à de nombreux étudiants.|Elle illustre la place durable des femmes dans l’enseignement supérieur du hadith.|al-Dhahabī, Siyar aʿlām al-nubalāʾ§Ibn Ḥajar, Tahdhīb al-tahdhīb
fatima-samarqandiyya|Fāṭima al-Samarqandiyya|فاطمة السمرقندية|500|581|aleppo|samarqand,aleppo|Fiqh|Hanafite|F|Juriste hanafite|Sa maîtrise du droit hanafite et son activité de conseil juridique.||Fille d’al-Samarqandī et épouse d’al-Kāsānī, elle fut décrite comme juriste accomplie.|Sa biographie rappelle la participation des femmes à la validation du savoir juridique.|al-Qurashī, al-Jawāhir al-muḍiyya§Ibn al-ʿAdīm, Bughyat al-ṭalab
zaynab-kamal|Zaynab bint al-Kamāl|زينب بنت الكمال|646|740|damascus|damascus,cairo|Hadith|Traditionniste|F|Musnida de Damas|De nombreuses licences et séances de transmission au VIIIe siècle.||Traditionniste damascène dont les auditions attirèrent plusieurs générations.|Elle représente la forte présence féminine dans les réseaux de samāʿ et d’ijāza.|al-Dhahabī, Muʿjam al-shuyūkh§Ibn Ḥajar, al-Durar al-kāmina
aisha-bauniyya|ʿĀʾisha al-Bāʿūniyya|عائشة الباعونية|865|922|damascus|damascus,cairo|Spiritualité,Poetry,Hadith|Shafiite|F|Poétesse et auteure spirituelle|Une œuvre abondante en prose et en poésie spirituelles.|al-Fatḥ al-mubīn§Fayḍ al-faḍl|Savante damascène issue d’une famille de juges, également active au Caire.|Elle est l’une des auteures musulmanes prémodernes les mieux conservées.|al-Ghazzī, al-Kawākib al-sāʾira§ʿĀʾisha al-Bāʿūniyya, œuvres éditées`;

    const scholars = parseRows(rows, ['id','name','arabic','born','died','city','routes','disciplines','school','gender','title','knownFor','works','bio','legacy','sources']).map((item) => ({
        ...item,
        born: Number(item.born),
        died: Number(item.died),
        routes: item.routes ? item.routes.split(',') : [],
        disciplines: item.disciplines ? item.disciplines.split(',') : [],
        works: item.works ? item.works.split('§') : [],
        sources: item.sources ? item.sources.split('§') : []
    }));

    const journeyRows = `four-imams|Les quatre écoles juridiques|Koufa, Médine, Le Caire et Bagdad|Suivre la formation des quatre grandes écoles sunnites à travers leurs fondateurs et leurs villes.|scale|#b7791f|abu-hanifa,malik,shafii,ahmad
hadith-rihla|La grande rihla du hadith|Des villes de Transoxiane aux capitales du savoir|Comparer les itinéraires des grands compilateurs et comprendre pourquoi le voyage était central dans la critique du hadith.|route|#0f766e|bukhari,muslim,abu-dawud,tirmidhi,nasai,ibn-majah,darimi
women-scholars|Femmes de savoir|Du premier siècle à l’époque ottomane|Découvrir des juristes, traditionnistes, récitatrices et auteures actives dans les grands réseaux savants.|sparkles|#be185d|aisha,umm-al-darda,amra,hafsa-sirin,karima-marwaziyya,fatima-samarqandiyya,zaynab-kamal,aisha-bauniyya
qiraat-centers|Les villes des lectures|La Mecque, Médine, Damas, Koufa et Bassora|Un parcours dans les foyers régionaux où se structurèrent les lectures canoniques du Coran.|book-open-check|#2563eb|ibn-kathir-reader,nafi,ibn-amir,asim,abu-amr-reader
arabic-schools|Les écoles de la langue arabe|Bassora, Koufa, Bagdad et Le Caire|Explorer la grammaire, la lexicographie, la rhétorique et la pensée linguistique arabe.|languages|#7c3aed|khalil,sibawayh,farra,jahiz,ibn-jinni,ibn-manzur
science-road|Sciences et horizons|Bagdad, Khwarazm, Le Caire, Cordoue et Maragha|Mathématiques, médecine, optique, géographie et astronomie dans un réseau intellectuel intercontinental.|telescope|#0369a1|khwarizmi,kindi,biruni,ibn-sina,ibn-haytham,zahrawi,idrisi,ibn-rushd,tusi
western-islam|Maghreb et al-Andalus|Kairouan, Ceuta, Cordoue, Grenade et Tunis|Le droit malikite, l’exégèse, la philosophie et l’histoire dans l’Occident musulman.|compass|#c2410c|sahnun,ibn-abd-al-barr,qadi-iyad,qurtubi,ibn-rushd,shatibi,ibn-khaldun`;

    const journeys = parseRows(journeyRows, ['id','title','subtitle','description','icon','accent','scholarIds']).map((item) => ({
        ...item,
        scholarIds: item.scholarIds.split(',')
    }));

    window.SCHOLAR_ATLAS_DATA.scholars.push(...scholars);
    window.SCHOLAR_ATLAS_DATA.journeys.push(...journeys);
})();
