(() => {
    const parseRows = window.__parseScholarAtlasRows;
    if (!parseRows || !window.SCHOLAR_ATLAS_DATA) throw new Error('Atlas Savants : base absente avant le lot femmes 4.');
    const rows = `fatima-fihri|Fāṭima al-Fihrī|فاطمة الفهرية|200|265|fez|kairouan,fez|Patronage,Education|Tradition de Fès|F|Fondatrice traditionnellement associée à al-Qarawiyyīn|La tradition qui lui attribue la fondation de la mosquée al-Qarawiyyīn à Fès.||Son histoire est connue surtout par des chroniques tardives et doit être présentée avec prudence documentaire.|Qu’elle soit lue comme biographie ou mémoire civique, sa figure symbolise le patronage féminin du savoir.|Ibn Abī Zarʿ, Rawḍ al-qirṭās§Chroniques de Fès, avec prudence critique
umm-khayr-baghdadiyya|Umm al-Khayr Fāṭima al-Baghdādiyya|أم الخير فاطمة البغدادية|450|532|baghdad|baghdad,makkah|Hadith|Traditionniste|F|Transmettrice bagdadienne|Des licences et auditions dans les réseaux de Bagdad et du pèlerinage.||Elle appartient à une génération de femmes dont les noms apparaissent dans les dictionnaires de maîtres et les certificats.|Son profil permet d’expliquer comment l’autorité se construisait par la chaîne, l’audition et la conservation des cahiers.|al-Samʿānī, al-Taḥbīr§al-Dhahabī, Siyar aʿlām al-nubalāʾ
sukayna-husayn|Sukayna bint al-Ḥusayn|سكينة بنت الحسين|47|117|madinah|madinah,makkah|Adab,Poetry,Sira|Ahl al-Bayt|F|Figure littéraire de Médine|Les salons littéraires et la mémoire de l’Ahl al-Bayt dans le Hedjaz omeyyade.||Fille d’al-Ḥusayn, elle est entourée de récits historiques et littéraires dont l’authenticité varie.|Sa réception éclaire la place des femmes dans la critique poétique et la sociabilité urbaine.|Abū al-Faraj al-Iṣfahānī, al-Aghānī§al-Balādhurī, Ansāb al-ashrāf
nana-asmau|Nana Asmāʾu|نانا أسماء|1208|1281|sokoto|sokoto|Education,Poetry,Fiqh,History|Sokoto|F|Éducatrice et auteure du califat de Sokoto|Un réseau d’éducation féminine, une production poétique multilingue et la transmission d’une culture savante ouest-africaine.|Poèmes didactiques en arabe, fulfulde et haoussa|Fille de ʿUthmān dan Fodio, elle forma des enseignantes et produisit des textes religieux, historiques et pédagogiques.|Son héritage montre comment le savoir islamique s’adapta aux langues et aux institutions de l’Afrique de l’Ouest.|Beverly Mack et Jean Boyd, One Woman’s Jihad§Corpus des œuvres de Nana Asmāʾu
rahmah-yunusiyah|Raḥmah al-Yūnusiyya|رحمة اليونسية|1318|1388|padang|padang,cairo|Education,Fiqh|Réformisme éducatif|F|Pionnière de l’éducation féminine en Indonésie|La fondation d’une institution destinée à la formation religieuse et générale des femmes.||Originaire de Minangkabau, elle développa un modèle scolaire articulant sciences religieuses, pédagogie et autonomie.|Son parcours élargit l’Atlas aux transformations modernes de l’enseignement musulman en Asie du Sud-Est.|Études historiques sur Diniyyah Puteri§Archives de l’éducation islamique indonésienne
aisha-abd-rahman|ʿĀʾisha ʿAbd al-Raḥmān, Bint al-Shāṭiʾ|عائشة عبد الرحمن بنت الشاطئ|1331|1419|cairo|damietta,cairo|Tafsir,Arabic,Literature|Université égyptienne|F|Exégète et professeure de littérature arabe|Une lecture littéraire du Coran et des travaux sur les femmes de la première communauté.|al-Tafsīr al-bayānī§Tarājim sayyidāt bayt al-nubuwwa|Formée à l’université égyptienne, elle enseigna la littérature et publia sous le nom de Bint al-Shāṭiʾ.|Son œuvre représente une étape importante de l’exégèse littéraire et de l’écriture académique féminine moderne.|ʿĀʾisha ʿAbd al-Raḥmān, al-Tafsīr al-bayānī§Études sur l’exégèse arabe moderne
zaynab-ghazali|Zaynab al-Ghazālī|زينب الغزالي|1335|1426|cairo|cairo|Education,Activism,Spiritualité|Mouvement associatif égyptien|F|Prédicatrice et organisatrice|L’éducation religieuse des femmes et une autobiographie marquée par l’engagement politique.|Ayyām min ḥayātī|Fondatrice d’une association féminine islamique, elle fut une voix importante du militantisme religieux égyptien du XXe siècle.|Sa trajectoire doit être lue dans le contexte des mouvements islamistes, de la répression d’État et de l’écriture autobiographique.|Zaynab al-Ghazālī, Ayyām min ḥayātī§Études sur les mouvements islamiques égyptiens`;
    const scholars = parseRows(rows, ['id','name','arabic','born','died','city','routes','disciplines','school','gender','title','knownFor','works','bio','legacy','sources']).map((item) => ({
        ...item,
        born: Number(item.born),
        died: Number(item.died),
        routes: item.routes ? item.routes.split(',') : [],
        disciplines: item.disciplines ? item.disciplines.split(',') : [],
        works: item.works ? item.works.split('§') : [],
        sources: item.sources ? item.sources.split('§') : []
    }));
    window.SCHOLAR_ATLAS_DATA.scholars.push(...scholars);
})();
