(() => {
    const parseRows = window.__parseScholarAtlasRows;
    if (!parseRows || !window.SCHOLAR_ATLAS_DATA) throw new Error('Atlas Savants : base absente avant le lot droit.');
    const rows = `abu-yusuf|Abū Yūsuf Yaʿqūb ibn Ibrāhīm|أبو يوسف يعقوب بن إبراهيم|113|182|baghdad|kufa,baghdad|Fiqh,Hadith,Administration|Hanafite|M|Juriste et grand cadi abbasside|La diffusion institutionnelle du droit hanafite et une réflexion ancienne sur les finances publiques.|Kitāb al-Kharāj§Ikhtilāf Abī Ḥanīfa wa-Ibn Abī Laylā|Formé à Koufa auprès d’Abū Ḥanīfa, il devint juge puis grand cadi sous les Abbassides.|Son œuvre relie raisonnement juridique, pratique judiciaire et gouvernement, tout en fixant une part importante de l’enseignement hanafite.|al-Khaṭīb al-Baghdādī, Tārīkh Baghdād§al-Dhahabī, Siyar aʿlām al-nubalāʾ
shaybani|Muḥammad ibn al-Ḥasan al-Shaybānī|محمد بن الحسن الشيباني|132|189|baghdad|wasit,kufa,madinah,baghdad,rayy|Fiqh,Hadith,International Law|Hanafite|M|Systématisateur du droit hanafite|La mise par écrit d’un vaste corpus juridique et les premiers grands traités de conduite des relations extérieures.|al-Aṣl§al-Jāmiʿ al-kabīr§al-Siyar al-kabīr|Élève d’Abū Ḥanīfa et d’Abū Yūsuf, il étudia aussi auprès de Mālik à Médine.|Ses ouvrages forment un socle documentaire de l’école hanafite et influencèrent la théorie du droit des relations internationales.|al-Sarakhsī, Sharḥ al-Siyar al-kabīr§al-Dhahabī, Siyar aʿlām al-nubalāʾ
zufar|Zufar ibn al-Hudhayl|زفر بن الهذيل|110|158|kufa|isfahan,basra,kufa|Fiqh,Hadith|Hanafite|M|Juriste du cercle d’Abū Ḥanīfa|Une forte maîtrise de l’analogie juridique et des avis parfois distincts de ceux de ses condisciples.||Né dans une famille liée à Ispahan, il étudia le hadith puis se consacra au fiqh à Koufa.|Ses opinions, conservées dans les ouvrages de l’école, montrent la pluralité interne du hanafisme ancien.|al-Qurashī, al-Jawāhir al-muḍiyya§al-Khaṭīb al-Baghdādī, Tārīkh Baghdād
tahawi|Abū Jaʿfar al-Ṭaḥāwī|أبو جعفر الطحاوي|239|321|cairo|cairo|Fiqh,Hadith,Theology|Hanafite|M|Juriste et traditionniste d’Égypte|La conciliation des traditions apparemment divergentes et une présentation influente de la doctrine sunnite.|Sharḥ Maʿānī al-āthār§Mushkil al-āthār§al-ʿAqīda al-Ṭaḥāwiyya|D’abord formé dans un milieu shafiite, il adopta ensuite le droit hanafite et devint une autorité égyptienne.|Son travail montre comment le fiqh peut dialoguer avec la critique des chaînes, la comparaison des textes et la théologie.|Ibn Yūnus, Tārīkh Miṣr§al-Dhahabī, Siyar aʿlām al-nubalāʾ
sarakhsi|Shams al-Aʾimma al-Sarakhsī|شمس الأئمة السرخسي|400|483|ferghana|bukhara,ferghana|Fiqh,Usul|Hanafite|M|Théoricien hanafite du droit|Une synthèse monumentale du fiqh et des fondements juridiques, en partie dictée pendant une détention.|al-Mabsūṭ§Uṣūl al-Sarakhsī§Sharḥ al-Siyar al-kabīr|Formé en Transoxiane, il appartint au grand milieu juridique hanafite de Boukhara.|Sa méthode articule doctrine, preuve, analogie, usages et finalités pratiques avec une ampleur exceptionnelle.|al-Sarakhsī, al-Mabsūṭ§al-Qurashī, al-Jawāhir al-muḍiyya
kasani|ʿAlāʾ al-Dīn al-Kāsānī|علاء الدين الكاساني|500|587|aleppo|ferghana,samarqand,aleppo|Fiqh,Usul|Hanafite|M|Auteur de Badāʾiʿ al-ṣanāʾiʿ|Une présentation structurée du droit hanafite selon les causes, conditions et effets des règles.|Badāʾiʿ al-ṣanāʾiʿ|Originaire d’Asie centrale, il étudia auprès dʾAlāʾ al-Dīn al-Samarqandī et épousa sa fille Fāṭima, juriste reconnue.|Son ouvrage reste une référence majeure pour comprendre l’architecture interne du raisonnement hanafite.|al-Qurashī, al-Jawāhir al-muḍiyya§Ibn al-ʿAdīm, Bughyat al-ṭalab
marghinani|Burhān al-Dīn al-Marghīnānī|برهان الدين المرغيناني|511|593|ferghana|ferghana,samarqand|Fiqh|Hanafite|M|Auteur d’al-Hidāya|Un manuel juridique condensant et argumentant les positions majeures du hanafisme.|al-Hidāya§Bidāyat al-mubtadiʾ|Né dans la vallée de Ferghana, il fut formé dans les réseaux savants de Transoxiane.|Al-Hidāya devint un texte central de l’enseignement hanafite de l’Asie centrale au sous-continent indien.|al-Qurashī, al-Jawāhir al-muḍiyya§al-Marghīnānī, al-Hidāya
ibn-qasim|ʿAbd al-Raḥmān Ibn al-Qāsim|عبد الرحمن بن القاسم|132|191|cairo|cairo,madinah|Fiqh|Malikite|M|Principal transmetteur égyptien de Mālik|La conservation et l’explication de nombreux avis de Mālik dans la tradition de la Mudawwana.||Il séjourna longuement à Médine auprès de Mālik avant de revenir enseigner en Égypte.|Par Saḥnūn et la Mudawwana, son enseignement devint décisif pour le malikisme du Maghreb et d’al-Andalus.|Qāḍī ʿIyāḍ, Tartīb al-madārik§Ibn Farḥūn, al-Dībāj al-mudhhab
ibn-wahb|ʿAbd Allāh ibn Wahb|عبد الله بن وهب|125|197|cairo|cairo,madinah,makkah|Hadith,Fiqh|Malikite|M|Juriste et traditionniste égyptien|Une vaste collecte de traditions et la transmission du droit de Mālik en Égypte.|al-Jāmiʿ§al-Muwaṭṭaʾ, recension d’Ibn Wahb|Il étudia auprès de Mālik, al-Layth ibn Saʿd et de nombreux traditionnistes du Hedjaz et d’Égypte.|Son profil illustre une branche malikite fortement ancrée dans le hadith et plus diverse que la seule transmission doctrinale.|Ibn ʿAbd al-Ḥakam, Futūḥ Miṣr, notices§al-Dhahabī, Siyar aʿlām al-nubalāʾ
ashhab|Ashhab ibn ʿAbd al-ʿAzīz|أشهب بن عبد العزيز|140|204|cairo|cairo,madinah|Fiqh|Malikite|M|Juriste malikite d’Égypte|Des avis juridiques indépendants et une transmission importante de l’enseignement de Mālik.||Formé en Égypte puis auprès de Mālik, il devint l’un des principaux juristes malikites de son milieu.|La comparaison de ses avis avec ceux d’Ibn al-Qāsim permet de saisir la diversité du malikisme ancien.|Qāḍī ʿIyāḍ, Tartīb al-madārik§Ibn Farḥūn, al-Dībāj al-mudhhab`;
    const scholars = parseRows(rows, ['id','name','arabic','born','died','city','routes','disciplines','school','gender','title','knownFor','works','bio','legacy','sources']).map((item) => ({
        ...item,
        born: Number(item.born), died: Number(item.died),
        routes: item.routes ? item.routes.split(',') : [],
        disciplines: item.disciplines ? item.disciplines.split(',') : [],
        works: item.works ? item.works.split('§') : [],
        sources: item.sources ? item.sources.split('§') : []
    }));
    window.SCHOLAR_ATLAS_DATA.scholars.push(...scholars);
})();
