(() => {
    const parseRows = window.__parseScholarAtlasRows;
    if (!parseRows || !window.SCHOLAR_ATLAS_DATA) throw new Error('Atlas Savants : base absente avant le lot lectures-langue.');
    const rows = `wahidi|ʿAlī ibn Aḥmad al-Wāḥidī|علي بن أحمد الواحدي|398|468|nishapur|nishapur|Tafsir,Arabic,Asbab al-Nuzul|Shafiite|M|Exégète de Nishapur|Des commentaires de niveaux différents et un ouvrage célèbre sur les circonstances de révélation.|al-Basīṭ§al-Wasīṭ§al-Wajīz§Asbāb al-nuzūl|Formé dans le milieu littéraire et shafiite de Nishapur, il fut notamment lié à al-Thaʿlabī.|Ses ouvrages ont fortement influencé l’exégèse postérieure, mais les récits d’asbāb doivent être évalués chaîne par chaîne.|al-Subkī, Ṭabaqāt al-shāfiʿiyya§al-Wāḥidī, Asbāb al-nuzūl
baghawi|al-Ḥusayn ibn Masʿūd al-Baghawī|الحسين بن مسعود البغوي|436|516|merv|merv|Tafsir,Hadith,Fiqh|Shafiite|M|Exégète et traditionniste du Khurasan|Une synthèse exégétique sobre et des compilations majeures de hadith et d’éthique.|Maʿālim al-tanzīl§Sharḥ al-sunna§Maṣābīḥ al-sunna|Originaire de la région de Baghshūr, il étudia et enseigna dans le Khurasan.|Ses ouvrages ont servi de pont entre l’exégèse transmise, le hadith et l’enseignement shafiite.|al-Dhahabī, Siyar aʿlām al-nubalāʾ§al-Subkī, Ṭabaqāt al-shāfiʿiyya
baydawi|Nāṣir al-Dīn al-Bayḍāwī|ناصر الدين البيضاوي|585|685|shiraz|shiraz|Tafsir,Fiqh,Usul,Theology|Shafiite / Asharite|M|Auteur d’Anwār al-tanzīl|Un commentaire condensé combinant langue, théologie et héritage de plusieurs tafsīrs antérieurs.|Anwār al-tanzīl§Minhāj al-wuṣūl|Juge et savant du Fars, il produisit des synthèses destinées à l’enseignement avancé.|Son tafsīr devint l’un des textes les plus commentés dans les madrasa, tout en nécessitant l’identification de ses sources doctrinales.|al-Subkī, Ṭabaqāt al-shāfiʿiyya§al-Bayḍāwī, Anwār al-tanzīl
abu-hayyan|Abū Ḥayyān al-Andalusī|أبو حيان الأندلسي|654|745|cairo|granada,ceuta,tunis,cairo|Arabic,Tafsir,Qiraat|École andalouse / Shafiite|M|Grammairien et exégète du Caire|Une exégèse particulièrement attentive à la syntaxe, aux lectures et à la critique grammaticale.|al-Baḥr al-muḥīṭ§al-Tadhyīl wa-l-takmīl|Originaire de Grenade, il voyagea au Maghreb puis s’établit au Caire, où il enseigna la langue et le tafsīr.|Son œuvre constitue une référence majeure pour l’analyse grammaticale du texte coranique et l’histoire des écoles linguistiques.|al-Suyūṭī, Bughyat al-wuʿāt§Abū Ḥayyān, al-Baḥr al-muḥīṭ
ibn-ashur|Muḥammad al-Ṭāhir Ibn ʿĀshūr|محمد الطاهر ابن عاشور|1296|1393|tunis|tunis|Tafsir,Usul,Fiqh,Arabic|Malikite|M|Exégète et théoricien des finalités|Une exégèse littéraire et réformatrice ainsi qu’une formulation moderne des maqāṣid.|al-Taḥrīr wa-l-tanwīr§Maqāṣid al-sharīʿa al-islāmiyya|Formé à la Zaytūna, il en fut enseignant puis grand imam dans un contexte de réformes et de domination coloniale.|Son œuvre articule langue, contexte, droit et finalités, et occupe une place majeure dans la pensée islamique contemporaine.|Ibn ʿĀshūr, al-Taḥrīr wa-l-tanwīr§Études sur la Zaytūna et les maqāṣid
hamza-zayyat|Ḥamza al-Zayyāt|حمزة الزيات|80|156|kufa|kufa|Qiraat,Hadith|Lectures de Koufa|M|Lecteur canonique de Koufa|Une lecture caractérisée par des choix précis d’allongement, d’arrêt et de réalisation phonétique.||Marchand d’huile selon son surnom, il reçut la récitation de maîtres de Koufa et la transmit notamment par Khalaf et Khallād.|Sa lecture témoigne de la diversité réglée des traditions de récitation kufiennes.|Ibn al-Jazarī, Ghāyat al-nihāya§al-Dhahabī, Maʿrifat al-qurrāʾ al-kibār
kisai|ʿAlī al-Kisāʾī|علي الكسائي|119|189|kufa|kufa,baghdad,rayy|Qiraat,Arabic|Lectures de Koufa|M|Lecteur canonique et grammairien|Une lecture canonique et une place fondatrice dans l’école grammaticale de Koufa.|Maʿānī al-Qurʾān, fragments et traditions|Il étudia la récitation et la langue, puis enseigna dans le milieu abbasside, notamment aux fils d’al-Rashīd.|Son profil illustre l’interaction entre qirāʾāt, observation des usages arabes et construction de la grammaire.|Ibn al-Jazarī, Ghāyat al-nihāya§al-Suyūṭī, Bughyat al-wuʿāt
abu-jafar-reader|Abū Jaʿfar Yazīd al-Madanī|أبو جعفر يزيد المدني|35|130|madinah|madinah|Qiraat|Lectures de Médine|M|Lecteur canonique de Médine|L’une des dix lectures canoniques, transmise par Ibn Wardān et Ibn Jammāz.||Appartenant aux premières générations médinoises, il enseigna la récitation dans la ville du Prophète.|Son inclusion parmi les dix lectures met en évidence la pluralité des voies médinoises au-delà de Nāfiʿ.|Ibn al-Jazarī, Ghāyat al-nihāya§al-Dhahabī, Maʿrifat al-qurrāʾ al-kibār
yaqub-hadrami|Yaʿqūb al-Ḥaḍramī|يعقوب الحضرمي|117|205|basra|basra|Qiraat,Arabic|Lectures de Bassora|M|Lecteur canonique de Bassora|Une lecture conservée par Ruways et Rawḥ et une solide maîtrise de la langue.||Il dirigea l’enseignement de la récitation à Bassora et fut reconnu pour la précision de sa performance et de ses chaînes.|Sa tradition complète le tableau des foyers bassoriens, souvent réduits à Abū ʿAmr seul.|Ibn al-Jazarī, Ghāyat al-nihāya§al-Dhahabī, Maʿrifat al-qurrāʾ al-kibār
warsh|Warsh, ʿUthmān ibn Saʿīd|ورش عثمان بن سعيد|110|197|cairo|cairo,madinah|Qiraat|Transmission de Nāfiʿ|M|Transmetteur de la lecture de Nāfiʿ|Une voie de récitation largement diffusée au Maghreb, en Afrique de l’Ouest et dans certaines régions du monde musulman.||Originaire d’Égypte, il voyagea à Médine pour étudier auprès de Nāfiʿ avant de revenir enseigner au Caire.|Sa transmission montre comment une voie locale devint une tradition transrégionale grâce aux réseaux d’enseignement.|Ibn al-Jazarī, Ghāyat al-nihāya§al-Dhahabī, Maʿrifat al-qurrāʾ al-kibār`;
    const scholars = parseRows(rows, ['id','name','arabic','born','died','city','routes','disciplines','school','gender','title','knownFor','works','bio','legacy','sources']).map((item) => ({
        ...item,
        born: Number(item.born), died: Number(item.died),
        routes: item.routes ? item.routes.split(',') : [],
        disciplines: item.disciplines ? item.disciplines.split(',') : [],
        works: item.works ? item.works.split('§') : [],
        sources: item.sources ? item.sources.split('§') : []
    }));
    window.SCHOLAR_ATLAS_DATA.scholars.push(...scholars);
})();
