(() => {
    const parseRows = window.__parseScholarAtlasRows;
    if (!parseRows || !window.SCHOLAR_ATLAS_DATA) throw new Error('Atlas Savants : base absente avant le lot femmes 3.');
    const rows = `fatima-abbas|Fāṭima bint ʿAbbās al-Baghdādiyya|فاطمة بنت عباس البغدادية|620|714|damascus|baghdad,damascus,cairo|Fiqh,Preaching,Spiritualité|Hanbalite|F|Juriste et prédicatrice|Son enseignement public, son engagement moral et sa maîtrise du fiqh hanbalite.||Originaire de Bagdad, elle enseigna au Levant et en Égypte et fut louée par plusieurs contemporains.|Sa carrière montre qu’une femme pouvait intervenir publiquement dans le droit, la prédication et la réforme sociale.|Ibn Taymiyya, mentions biographiques rapportées§Ibn Kathīr, al-Bidāya wa-l-nihāya
sitt-wuzara|Sitt al-Wuzarāʾ bint ʿUmar|ست الوزراء بنت عمر|624|716|damascus|damascus,cairo|Hadith|Traditionniste|F|Autorité de transmission|La lecture et la transmission de recueils majeurs, notamment dans les réseaux syro-égyptiens.||Elle reçut des auditions dès l’enfance et enseigna pendant des décennies à Damas.|Son parcours illustre la construction d’une autorité documentaire sur le temps long.|al-Dhahabī, Muʿjam al-shuyūkh§Ibn Ḥajar, al-Durar al-kāmina
fatima-batayahiyya|Fāṭima al-Baṭāʾiḥiyya|فاطمة البطائحية|620|711|damascus|baghdad,damascus|Hadith|Traditionniste|F|Transmettrice du hadith|Des auditions recherchées par les grands traditionnistes du VIIe siècle.||Installée à Damas, elle transmit à un vaste cercle d’étudiants et d’enseignants.|Sa présence dans les dictionnaires de maîtres rappelle la normalité de l’apprentissage auprès de femmes.|al-Dhahabī, Muʿjam al-shuyūkh§Ibn Ḥajar, al-Durar al-kāmina
hajar-dimashqiyya|Hajar bint Muḥammad al-Dimashqiyya|هجر بنت محمد الدمشقية|725|803|damascus|damascus|Hadith|Traditionniste|F|Musnida damascène|Une longue carrière de transmission dans les milieux du hadith mamelouk.||Elle reçut des auditions tôt dans sa vie et enseigna à plusieurs savants de premier plan.|Son dossier permet d’étudier concrètement l’ijāza, l’audition et la longévité des chaînes.|Ibn Ḥajar, al-Durar al-kāmina§al-Sakhāwī, al-Ḍawʾ al-lāmiʿ
aisha-abd-hadi|ʿĀʾisha bint ʿAbd al-Hādī|عائشة بنت عبد الهادي|723|816|damascus|damascus|Hadith|Hanbalite|F|Transmettrice du Ṣaḥīḥ al-Bukhārī|Une version réputée du Ṣaḥīḥ et un enseignement recherché à Damas.||Issue d’une famille hanbalite, elle transmit dans le complexe ṣāliḥiyya à des étudiants venus de nombreuses régions.|Sa carrière est un cas majeur de l’autorité féminine dans la transmission d’un texte canonique.|Ibn Ḥajar, al-Durar al-kāmina§al-Sakhāwī, al-Ḍawʾ al-lāmiʿ
umm-hani-huriniyya|Umm Hāniʾ Maryam al-Ḥurīniyya|أم هانئ مريم الحورينية|780|871|cairo|damascus,cairo,makkah|Hadith,Fiqh|Shafiite|F|Traditionniste et juriste|Ses licences, ses voyages et son enseignement dans les réseaux du IXe siècle.||Elle étudia auprès de nombreux maîtres, accomplit le pèlerinage et transmit au Caire.|Sa notice montre la continuité de la rihla féminine dans le monde mamelouk tardif.|al-Sakhāwī, al-Ḍawʾ al-lāmiʿ§Ibn Fahd, Muʿjam al-shuyūkh
sutayta-mahamali|Sutayta al-Maḥāmilī|ستيتة المحاملي|300|377|baghdad|baghdad|Fiqh,Mathematics|Shafiite|F|Juriste et spécialiste du calcul|Sa maîtrise du droit successoral, des transactions et des calculs nécessaires aux partages.||Issue d’une famille de juristes bagdadiens, elle est décrite comme compétente dans le fiqh et les mathématiques appliquées.|Son exemple rappelle le lien pratique entre droit, fractions et calcul dans la science des successions.|al-Khaṭīb al-Baghdādī, Tārīkh Baghdād§Ibn al-Jawzī, al-Muntaẓam
lubna-cordoba|Lubnā de Cordoue|لبنى القرطبية|320|374|cordoba|cordoba|Mathematics,Calligraphy,Library|Cour omeyyade d’al-Andalus|F|Copiste, bibliothécaire et mathématicienne|Son activité dans la bibliothèque califale et sa compétence dans le calcul et la copie savante.||Associée à la cour d’al-Ḥakam II, elle participa à la culture du livre et à l’administration d’une grande bibliothèque.|Sa figure ouvre une fenêtre sur les métiers savants féminins de la cour cordouane.|Ibn Bashkuwāl, al-Ṣila, traditions biographiques§Sources andalouses sur la cour d’al-Ḥakam II`;
    const scholars = parseRows(rows, ['id','name','arabic','born','died','city','routes','disciplines','school','gender','title','knownFor','works','bio','legacy','sources']).map((item) => ({
        ...item,
        born: Number(item.born),
        died: Number(item.died),
        routes: item.routes ? item.routes.split(',') : [],
        disciplines: item.disciplines ? item.disciplines.split(',') : [],
        works: item.works ? item.works.split('§') : [],
        sources: item.sources ? item.sources.split('§') : []
    }));
    window.SCHOLAR_ATLAS_DATA.scholars.push(...scholars);
})();
