(() => {
    const parseRows = window.__parseScholarAtlasRows;
    if (!parseRows || !window.SCHOLAR_ATLAS_DATA) throw new Error('Atlas Savants : base absente avant le lot femmes 2.');
    const rows = `fatima-mundhir|Fāṭima bint al-Mundhir|فاطمة بنت المنذر|48|140|madinah|madinah|Hadith,Fiqh|École de Médine|F|Traditionniste médinoise|Sa transmission familiale, notamment à son époux Hishām ibn ʿUrwa, de traditions issues d’Asmāʾ bint Abī Bakr.||Issue d’une famille de traditionnistes, elle participa à la continuité des savoirs médinois par les réseaux de parenté et d’étude.|Son cas montre que des hommes reconnus pouvaient recevoir le hadith de femmes de leur propre famille.|Ibn Saʿd, al-Ṭabaqāt al-kubrā§Ibn Ḥajar, Tahdhīb al-tahdhīb
muadha-adawiyya|Muʿādha al-ʿAdawiyya|معاذة العدوية|20|83|basra|basra|Hadith,Fiqh,Spiritualité|École de Bassora|F|Traditionniste et ascète de Bassora|La transmission d’après ʿĀʾisha et une réputation de discipline spirituelle.||Elle appartint aux premiers cercles féminins de Bassora et transmit à plusieurs élèves, femmes et hommes.|Sa figure relie hadith, pratique cultuelle et ascèse sans confondre ces domaines.|Ibn Saʿd, al-Ṭabaqāt al-kubrā§al-Dhahabī, Siyar aʿlām al-nubalāʾ
rabia-adawiyya|Rābiʿa al-ʿAdawiyya|رابعة العدوية|95|185|basra|basra|Spiritualité,Poetry|Ascèse de Bassora|F|Figure majeure de l’amour spirituel|La mémoire d’une ascèse centrée sur la sincérité et l’amour de Dieu.||Les récits sur sa vie sont tardifs et mêlent histoire, exemplum spirituel et littérature hagiographique.|Son langage de l’amour divin a profondément marqué les traditions spirituelles et poétiques.|Abū Nuʿaym, Ḥilyat al-awliyāʾ§ʿAṭṭār, Tadhkirat al-awliyāʾ
nafisa-hasan|Nafīsa bint al-Ḥasan|نفيسة بنت الحسن|145|208|cairo|madinah,cairo|Hadith,Fiqh,Spiritualité|Ahl al-Bayt|F|Enseignante et figure pieuse du Caire|Des cercles d’enseignement, une ascendance husaynide et une forte mémoire dévotionnelle en Égypte.||Née à Médine et établie en Égypte, elle est associée à l’enseignement, à la piété et à des traditions de visite.|Son héritage combine autorité savante, sainteté locale et mémoire de l’Ahl al-Bayt.|al-Dhahabī, Siyar aʿlām al-nubalāʾ§al-Sakhāwī, al-Tuḥfa al-laṭīfa
shuhda-katiba|Shuhda al-Kātiba|شهدة الكاتبة|482|574|baghdad|baghdad|Hadith,Calligraphy,Adab|Traditionniste|F|Musnida et calligraphe de Bagdad|Ses séances de hadith et sa réputation dans l’écriture et la culture littéraire.||Connue comme « la fierté des femmes », elle enseigna à Bagdad à un large public et transmit des ouvrages importants.|Elle illustre l’articulation entre maîtrise documentaire, écriture et autorité de transmission.|Ibn al-Jawzī, al-Muntaẓam§al-Dhahabī, Siyar aʿlām al-nubalāʾ
fatima-sad-khayr|Fāṭima bint Saʿd al-Khayr|فاطمة بنت سعد الخير|522|600|baghdad|isfahan,baghdad,damascus,cairo|Hadith|Traditionniste|F|Voyageuse du hadith|Un itinéraire exceptionnel entre l’Iran, l’Irak, le Levant et l’Égypte.||Issue d’une famille de traditionnistes itinérants, elle reçut et transmit des auditions dans plusieurs métropoles.|Son parcours rend visible la mobilité féminine dans les réseaux d’ijāza et de samāʿ.|al-Dhahabī, Siyar aʿlām al-nubalāʾ§Ibn al-Najjār, Dhayl Tārīkh Baghdād
zaynab-shari|Zaynab bint al-Shaʿrī|زينب بنت الشعري|524|615|nishapur|nishapur,baghdad,damascus|Hadith|Traditionniste|F|Musnida du Khurasan|La transmission de nombreux recueils et parties de hadith à des étudiants venus de loin.||Elle reçut des licences d’un grand nombre de maîtres et devint une autorité recherchée pour la hauteur de ses chaînes.|Sa carrière témoigne de la revitalisation de l’enseignement féminin du hadith aux VIe-VIIe siècles.|al-Dhahabī, Siyar aʿlām al-nubalāʾ§Ibn al-Najjār, Dhayl Tārīkh Baghdād
zaynab-makki|Zaynab bint Makkī|زينب بنت مكي|594|688|damascus|damascus|Hadith|Traditionniste|F|Musnida de Damas|Ses auditions de recueils et sa place dans les chaînes damascènes du VIIe siècle.||Elle enseigna à un âge avancé et fut recherchée par des traditionnistes pour ses transmissions anciennes.|Son exemple montre le rôle de la longévité et de la documentation des auditions dans l’autorité savante.|al-Dhahabī, Muʿjam al-shuyūkh§Ibn Ḥajar, al-Durar al-kāmina`;
    const scholars = parseRows(rows, ['id','name','arabic','born','died','city','routes','disciplines','school','gender','title','knownFor','works','bio','legacy','sources']).map((item) => ({
        ...item,
        born: Number(item.born),
        died: Number(item.died),
        routes: item.routes ? item.routes.split(',') : [],
        disciplines: item.disciplines ? item.disciplines.split(',') : [],
        works: item.works ? item.works.split('§') : [],
        sources: item.sources ? item.sources.split('§') : []
    }));
    window.SCHOLAR_ATLAS_DATA.scholars.push(...scholars);
})();
