(() => {
    const parseRows = window.__parseScholarAtlasRows;
    if (!parseRows || !window.SCHOLAR_ATLAS_DATA) throw new Error('Atlas Savants : base absente avant le lot femmes 1.');
    const rows = `hafsa-umar|Ḥafṣa bint ʿUmar|حفصة بنت عمر|-18|45|madinah|makkah,madinah|Hadith,Quran|Premières générations|F|Mère des croyants et gardienne d’un codex|Sa transmission du hadith et son association à la conservation d’un exemplaire écrit du Coran.||Fille de ʿUmar ibn al-Khaṭṭāb et épouse du Prophète, elle participa aux premiers réseaux médinois de transmission.|Sa biographie relie mémoire familiale, transmission prophétique et histoire de la collecte coranique.|Ibn Saʿd, al-Ṭabaqāt al-kubrā§Ibn Ḥajar, al-Iṣāba
umm-salama|Umm Salama Hind bint Abī Umayya|أم سلمة هند بنت أبي أمية|-28|62|madinah|makkah,abyssinia,madinah|Hadith,Fiqh,Sira|Premières générations|F|Mère des croyants et conseillère|Un vaste corpus de traditions, notamment sur le culte, la famille et plusieurs épisodes de la Sīra.||Migrante en Abyssinie puis à Médine, elle fut reconnue pour sa mémoire, son jugement et la précision de ses récits.|Ses avis et narrations constituent une source importante pour l’histoire religieuse et sociale des débuts de l’islam.|Ibn Saʿd, al-Ṭabaqāt al-kubrā§Ibn Ḥajar, al-Iṣāba
asma-abi-bakr|Asmāʾ bint Abī Bakr|أسماء بنت أبي بكر|-27|73|madinah|makkah,madinah|Hadith,Sira|Premières générations|F|Transmettrice et témoin des premières générations|Ses récits sur l’Hégire, la vie familiale et plusieurs pratiques cultuelles.||Sœur de ʿĀʾisha et mère de ʿAbd Allāh ibn al-Zubayr, elle vécut jusqu’à un âge avancé et transmit à plusieurs générations.|Sa longue vie fait d’elle un lien entre l’époque prophétique et les débats politiques du premier siècle.|Ibn Saʿd, al-Ṭabaqāt al-kubrā§al-Dhahabī, Siyar aʿlām al-nubalāʾ
maymuna|Maymūna bint al-Ḥārith|ميمونة بنت الحارث|-29|51|madinah|makkah,madinah|Hadith,Fiqh|Premières générations|F|Mère des croyants et transmettrice|Des traditions relatives à la purification, à la vie domestique et au pèlerinage.||Dernière femme épousée par le Prophète selon une chronologie courante, elle transmit à des proches et à des successeurs.|Son réseau familial relia plusieurs maisons influentes du Hedjaz.|Ibn Saʿd, al-Ṭabaqāt al-kubrā§Ibn Ḥajar, al-Iṣāba
umm-habiba|Umm Ḥabība Ramla bint Abī Sufyān|أم حبيبة رملة بنت أبي سفيان|-25|44|madinah|makkah,abyssinia,madinah|Hadith,Sira|Premières générations|F|Migrante et mère des croyants|Des récits sur l’émigration en Abyssinie, la prière et la vie prophétique.||Elle connut l’exil en Abyssinie avant de rejoindre Médine et transmit plusieurs traditions aux générations suivantes.|Sa trajectoire éclaire les circulations précoces entre La Mecque, l’Abyssinie et Médine.|Ibn Saʿd, al-Ṭabaqāt al-kubrā§Ibn Ḥajar, al-Iṣāba
fatima-zahra|Fāṭima al-Zahrāʾ|فاطمة الزهراء|-18|11|madinah|makkah,madinah|Sira,Ethics|Ahl al-Bayt|F|Fille du Prophète et figure de l’Ahl al-Bayt|Sa place dans la famille prophétique, la piété domestique et la mémoire des premières générations.||Épouse de ʿAlī et mère d’al-Ḥasan et al-Ḥusayn, elle occupe une place centrale dans les mémoires sunnites et chiites.|Son héritage est religieux, familial et symbolique, avec des lectures confessionnelles diverses.|Ibn Saʿd, al-Ṭabaqāt al-kubrā§al-Balādhurī, Ansāb al-ashrāf
safiyya-huyayy|Ṣafiyya bint Ḥuyayy|صفية بنت حيي|-10|50|madinah|khaybar,madinah|Hadith,Sira|Premières générations|F|Mère des croyants et transmettrice|Des traditions sur la vie du Prophète et l’intégration de différentes lignées dans la communauté médinoise.||Issue des Banū al-Naḍīr, elle devint épouse du Prophète après Khaybar et transmit à des proches et successeurs.|Sa biographie demande une lecture attentive des récits de conquête, de famille et de mémoire communautaire.|Ibn Saʿd, al-Ṭabaqāt al-kubrā§Ibn Ḥajar, al-Iṣāba
shifa-adawiyya|al-Shifāʾ bint ʿAbd Allāh|الشفاء بنت عبد الله|-20|20|madinah|makkah,madinah|Fiqh,Administration,Literacy|Premières générations|F|Compagne lettrée et actrice de la vie civique|Son association à l’écriture, à l’enseignement et à la vie du marché médinois.||Parmi les femmes mecquoises sachant écrire, elle est mentionnée dans les récits de transmission et d’organisation urbaine.|Sa notice rappelle que la compétence savante pouvait aussi prendre la forme d’une expertise pratique et administrative.|Ibn Saʿd, al-Ṭabaqāt al-kubrā§Ibn Ḥajar, al-Iṣāba`;
    const scholars = parseRows(rows, ['id','name','arabic','born','died','city','routes','disciplines','school','gender','title','knownFor','works','bio','legacy','sources']).map((item) => ({
        ...item,
        born: Number(item.born),
        died: Number(item.died),
        routes: item.routes ? item.routes.split(',') : [],
        disciplines: item.disciplines ? item.disciplines.split(',') : [],
        works: item.works ? item.works.split('§') : [],
        sources: item.sources ? item.sources.split('§') : []
    }));
    window.SCHOLAR_ATLAS_DATA.scholars.push(...scholars);
})();
