(() => {
    const parseRows = window.__parseScholarAtlasRows;
    const rows = `aisha|ʿĀʾisha bint Abī Bakr|عائشة بنت أبي بكر|-9|58|madinah|makkah,madinah|Hadith,Fiqh|Premières générations|F|Mère des croyants, juriste et transmettrice|Une autorité majeure pour le hadith, le droit familial et la vie du Prophète.||Compagne du Prophète et figure centrale de la transmission médinoise.|Son enseignement montre le rôle décisif des femmes dans la formation des savoirs islamiques.|Ibn Saʿd, al-Ṭabaqāt al-kubrā§al-Dhahabī, Siyar aʿlām al-nubalāʾ
umm-al-darda|Umm al-Dardāʾ al-Ṣughrā|أم الدرداء الصغرى|20|81|damascus|madinah,damascus|Hadith,Fiqh|Premières générations|F|Enseignante du Levant|Des cercles d’enseignement fréquentés par des hommes et des femmes à Damas.||Traditionniste et juriste du premier siècle de l’Hégire.|Elle incarne l’autorité publique de plusieurs enseignantes des premières générations.|Ibn Ḥajar, Tahdhīb al-tahdhīb§al-Dhahabī, Siyar aʿlām al-nubalāʾ
amra|ʿAmra bint ʿAbd al-Raḥmān|عمرة بنت عبد الرحمن|29|98|madinah|madinah|Hadith,Fiqh|École de Médine|F|Autorité médinoise du hadith|Sa transmission de ʿĀʾisha et sa maîtrise du droit médinois.||Successeure réputée pour sa connaissance des traditions de ʿĀʾisha.|Son parcours illustre la continuité féminine des réseaux de transmission.|Ibn Saʿd, al-Ṭabaqāt al-kubrā§Ibn Ḥajar, Tahdhīb al-tahdhīb
hafsa-sirin|Ḥafṣa bint Sīrīn|حفصة بنت سيرين|31|101|basra|basra|Hadith,Qiraat,Spiritualité|École de Bassora|F|Récitatrice et traditionniste|Sa maîtrise précoce du Coran et son enseignement à Bassora.||Savante de la génération des successeurs, reconnue pour le hadith et la récitation.|Elle offre un exemple ancien de spécialisation féminine dans les sciences coraniques.|Ibn Saʿd, al-Ṭabaqāt al-kubrā§al-Dhahabī, Siyar aʿlām al-nubalāʾ
hasan-basri|al-Ḥasan al-Baṣrī|الحسن البصري|21|110|basra|madinah,basra|Hadith,Fiqh,Spiritualité|École de Bassora|M|Prédicateur et maître de Bassora|Son enseignement moral, son éloquence et sa place dans la mémoire spirituelle.||Successeur majeur établi à Bassora, connu pour l’éthique et la prédication.|Sa figure relie les premières sciences religieuses aux traditions d’ascèse.|Abū Nuʿaym, Ḥilyat al-awliyāʾ§al-Dhahabī, Siyar aʿlām al-nubalāʾ
ibn-sirin|Muḥammad ibn Sīrīn|محمد بن سيرين|33|110|basra|basra|Hadith,Fiqh|École de Bassora|M|Traditionniste de Bassora|Sa prudence dans la transmission et ses avis juridiques.||Successeur de Bassora reconnu pour sa rigueur dans l’examen des récits.|Son nom est associé à l’attention ancienne portée aux chaînes de transmission.|Muslim, Introduction du Ṣaḥīḥ§al-Dhahabī, Siyar aʿlām al-nubalāʾ
zuhri|Ibn Shihāb al-Zuhrī|ابن شهاب الزهري|50|124|madinah|madinah,damascus|Hadith,History|École de Médine|M|Traditionniste et collecteur du hadith|Un rôle important dans la collecte et l’organisation précoce des traditions.||Actif entre le Hedjaz et le milieu omeyyade, il transmit un vaste corpus.|Il occupe une place centrale dans l’histoire de la mise par écrit du hadith.|Ibn Ḥajar, Tahdhīb al-tahdhīb§al-Dhahabī, Siyar aʿlām al-nubalāʾ
nafi|Nāfiʿ al-Madanī|نافع المدني|70|169|madinah|madinah|Qiraat|Lectures de Médine|M|Lecteur de Médine|L’une des dix lectures canoniques, transmise par Qālūn et Warsh.||Maître de récitation à Médine.|Sa voie demeure l’une des traditions de récitation les plus pratiquées.|Ibn al-Jazarī, Ghāyat al-nihāya§al-Dhahabī, Maʿrifat al-qurrāʾ al-kibār
ibn-kathir-reader|Ibn Kathīr al-Makkī|ابن كثير المكي|45|120|makkah|makkah|Qiraat|Lectures de La Mecque|M|Lecteur de La Mecque|L’une des lectures canoniques de la tradition mecquoise.||Maître de récitation de la première époque.|Sa lecture est conservée par les voies d’al-Bazzī et de Qunbul.|Ibn al-Jazarī, Ghāyat al-nihāya§al-Dhahabī, Maʿrifat al-qurrāʾ al-kibār
ibn-amir|Ibn ʿĀmir al-Dimashqī|ابن عامر الدمشقي|21|118|damascus|damascus|Qiraat,Fiqh|Lectures de Damas|M|Lecteur du Levant|La lecture canonique associée à Damas.||Lecteur et juge rattaché aux premières générations du Levant.|Sa lecture représente l’un des grands foyers régionaux de récitation.|Ibn al-Jazarī, Ghāyat al-nihāya§al-Dhahabī, Maʿrifat al-qurrāʾ al-kibār
asim|ʿĀṣim ibn Abī al-Najūd|عاصم بن أبي النجود|45|127|kufa|kufa|Qiraat,Hadith|Lectures de Koufa|M|Lecteur de Koufa|Sa lecture, transmise notamment par Ḥafṣ et Shuʿba.||Maître de récitation dans le grand foyer savant de Koufa.|La transmission de Ḥafṣ d’après ʿĀṣim est aujourd’hui largement diffusée.|Ibn al-Jazarī, Ghāyat al-nihāya§al-Dhahabī, Maʿrifat al-qurrāʾ al-kibār
abu-amr-reader|Abū ʿAmr ibn al-ʿAlāʾ|أبو عمرو بن العلاء|68|154|basra|makkah,madinah,basra,kufa|Qiraat,Arabic|Lectures de Bassora|M|Lecteur et linguiste|Une lecture canonique et une autorité dans la langue arabe.||Figure des premiers cercles de grammaire et de récitation à Bassora.|Son profil illustre le lien entre qirāʾāt et sciences de la langue.|Ibn al-Jazarī, Ghāyat al-nihāya§al-Suyūṭī, Bughyat al-wuʿāt
abu-hanifa|Abū Ḥanīfa al-Nuʿmān|أبو حنيفة النعمان|80|150|kufa|kufa,makkah|Fiqh,Theology|Hanafite|M|Imam de l’école hanafite|Une méthode juridique développée dans le milieu savant de Koufa.|al-Fiqh al-akbar (attribution discutée)|Juriste dont l’enseignement fut systématisé par Abū Yūsuf et al-Shaybānī.|L’école hanafite devint l’une des principales traditions juridiques du monde musulman.|al-Khaṭīb al-Baghdādī, Tārīkh Baghdād§al-Dhahabī, Siyar aʿlām al-nubalāʾ
malik|Mālik ibn Anas|مالك بن أنس|93|179|madinah|madinah|Fiqh,Hadith|Malikite|M|Imam de Médine|Le Muwaṭṭaʾ et l’importance accordée à la pratique médinoise.|al-Muwaṭṭaʾ|Juriste et traditionniste dont les étudiants venaient de nombreuses régions.|Son école se diffusa largement au Maghreb, en al-Andalus et en Afrique.|Qāḍī ʿIyāḍ, Tartīb al-madārik§al-Dhahabī, Siyar aʿlām al-nubalāʾ
shafii|Muḥammad ibn Idrīs al-Shāfiʿī|محمد بن إدريس الشافعي|150|204|cairo|gaza,makkah,madinah,baghdad,cairo|Fiqh,Usul,Hadith|Shafiite|M|Juriste et théoricien du droit|La Risāla et une formulation influente des fondements de la preuve.|al-Risāla§al-Umm|Formé au Hedjaz, actif en Irak puis en Égypte.|Il joua un rôle majeur dans la structuration de l’uṣūl al-fiqh.|al-Bayhaqī, Manāqib al-Shāfiʿī§al-Dhahabī, Siyar aʿlām al-nubalāʾ
ahmad|Aḥmad ibn Ḥanbal|أحمد بن حنبل|164|241|baghdad|baghdad,kufa,basra,makkah,madinah,sanaa|Hadith,Fiqh|Hanbalite|M|Traditionniste de Bagdad|Le Musnad et son attachement à la transmission textuelle.|al-Musnad|Grand voyageur du hadith et figure de Bagdad.|Son parcours devint un modèle de collecte, de patience et d’enseignement.|Ibn al-Jawzī, Manāqib al-imām Aḥmad§al-Dhahabī, Siyar aʿlām al-nubalāʾ
sahnun|Saḥnūn ibn Saʿīd|سحنون بن سعيد|160|240|kairouan|kairouan,cairo,madinah|Fiqh|Malikite|M|Juriste de Kairouan|La Mudawwana, texte majeur du malikisme ancien.|al-Mudawwana al-kubrā|Juriste d’Ifrīqiya qui voyagea en Orient avant d’enseigner à Kairouan.|Son œuvre façonna durablement la doctrine malikite occidentale.|Qāḍī ʿIyāḍ, Tartīb al-madārik§Ibn Farḥūn, al-Dībāj al-mudhhab
ibn-abd-al-barr|Ibn ʿAbd al-Barr|ابن عبد البر|368|463|cordoba|cordoba,valencia,denia|Hadith,Fiqh,History|Malikite|M|Traditionniste d’al-Andalus|Des synthèses majeures sur le Muwaṭṭaʾ, les compagnons et le savoir.|al-Tamhīd§al-Istidhkār§al-Istīʿāb|Savants andalou de premier plan, spécialiste du hadith et du fiqh.|Ses ouvrages demeurent des références centrales du malikisme.|Ibn Bashkuwāl, al-Ṣila§al-Dhahabī, Siyar aʿlām al-nubalāʾ
qadi-iyad|Qāḍī ʿIyāḍ|القاضي عياض|476|544|ceuta|ceuta,cordoba,granada,marrakesh|Fiqh,Hadith,Biography|Malikite|M|Juge et traditionniste du Maghreb|al-Shifāʾ et Tartīb al-madārik.|al-Shifāʾ§Tartīb al-madārik|Juriste de Ceuta, juge et auteur d’ouvrages influents.|Son œuvre relie droit, hadith, biographie et identité savante du Maghreb.|Ibn Farḥūn, al-Dībāj al-mudhhab§al-Dhahabī, Siyar aʿlām al-nubalāʾ
qarafi|Shihāb al-Dīn al-Qarāfī|شهاب الدين القرافي|626|684|cairo|cairo|Fiqh,Usul,Legal Theory|Malikite|M|Théoricien malikite du droit|Une analyse fine des distinctions juridiques, des finalités et du contexte.|al-Furūq§al-Dhakhīra§Sharḥ Tanqīḥ al-fuṣūl|Juriste malikite du Caire formé dans le milieu des madrasas égyptiennes.|Ses distinctions entre règles, avis, coutumes et fonctions restent très étudiées.|Ibn Farḥūn, al-Dībāj al-mudhhab§al-Qarāfī, al-Furūq
shatibi|Abū Isḥāq al-Shāṭibī|أبو إسحاق الشاطبي|720|790|granada|granada|Usul,Fiqh,Arabic|Malikite|M|Théoricien des finalités du droit|al-Muwāfaqāt et une réflexion influente sur les objectifs de la loi.|al-Muwāfaqāt§al-Iʿtiṣām|Juriste de Grenade actif dans les sciences juridiques et linguistiques.|Son œuvre est centrale dans les études sur les maqāṣid al-sharīʿa.|al-Shāṭibī, al-Muwāfaqāt§Aḥmad Bābā, Nayl al-ibtihāj
bukhari|Muḥammad al-Bukhārī|محمد البخاري|194|256|bukhara|bukhara,makkah,madinah,basra,kufa,baghdad,nishapur|Hadith,Biography|Traditionniste|M|Compilateur du Ṣaḥīḥ|al-Jāmiʿ al-ṣaḥīḥ et l’histoire des transmetteurs.|Ṣaḥīḥ al-Bukhārī§al-Tārīkh al-kabīr|Traditionniste de Boukhara ayant voyagé largement pour collecter et comparer.|Son Ṣaḥīḥ compte parmi les recueils les plus influents de la tradition sunnite.|al-Dhahabī, Siyar aʿlām al-nubalāʾ§Ibn Ḥajar, Hady al-sārī
muslim|Muslim ibn al-Ḥajjāj|مسلم بن الحجاج|204|261|nishapur|nishapur,makkah,madinah,basra,kufa,baghdad|Hadith|Traditionniste|M|Compilateur du Ṣaḥīḥ|Une organisation rigoureuse des variantes de chaînes et de textes.|Ṣaḥīḥ Muslim|Traditionniste de Nishapur, élève de nombreux maîtres de l’Orient.|Son recueil constitue un monument de la critique et de l’agencement du hadith.|al-Dhahabī, Siyar aʿlām al-nubalāʾ§al-Nawawī, Sharḥ Ṣaḥīḥ Muslim
abu-dawud|Abū Dāwūd al-Sijistānī|أبو داود السجستاني|202|275|basra|sijistan,baghdad,basra,makkah,damascus|Hadith,Fiqh|Traditionniste|M|Auteur des Sunan|Un recueil orienté vers les hadiths juridiques.|Sunan Abī Dāwūd|Traditionniste originaire du Sijistan, établi à Bassora après de nombreux voyages.|Ses Sunan devinrent un outil majeur pour l’étude du droit fondé sur le hadith.|al-Dhahabī, Siyar aʿlām al-nubalāʾ§Ibn Ḥajar, Tahdhīb al-tahdhīb
tirmidhi|Abū ʿĪsā al-Tirmidhī|أبو عيسى الترمذي|209|279|tirmidh|tirmidh,bukhara,nishapur,kufa,basra,makkah|Hadith,Fiqh|Traditionniste|M|Auteur du Jāmiʿ|L’association du hadith, de son degré et des avis juridiques.|Jāmiʿ al-Tirmidhī§al-Shamāʾil|Traditionniste de Tirmidh, connu pour une méthode reliant texte et pratique.|Son Jāmiʿ éclaire la réception juridique des hadiths.|al-Dhahabī, Siyar aʿlām al-nubalāʾ§Ibn Ḥajar, Tahdhīb al-tahdhīb
nasai|Aḥmad al-Nasāʾī|أحمد النسائي|215|303|cairo|nasa,nishapur,damascus,cairo|Hadith|Traditionniste|M|Auteur des Sunan|Une sélection exigeante des traditions et des transmetteurs.|al-Sunan al-kubrā§al-Mujtabā|Traditionniste originaire de Nasa, voyageur puis enseignant en Égypte.|Son recueil figure parmi les Six Livres de hadith sunnites.|al-Dhahabī, Siyar aʿlām al-nubalāʾ§Ibn Ḥajar, Tahdhīb al-tahdhīb
ibn-majah|Ibn Mājah al-Qazwīnī|ابن ماجه القزويني|209|273|qazvin|qazvin,kufa,basra,baghdad,damascus,cairo|Hadith,History|Traditionniste|M|Auteur des Sunan|Un recueil de hadiths et une activité d’historien.|Sunan Ibn Mājah|Traditionniste de Qazvin ayant voyagé dans les principaux centres de collecte.|Son Sunan fut intégré au canon des Six Livres dans une large tradition.|al-Dhahabī, Siyar aʿlām al-nubalāʾ§Ibn Ḥajar, Tahdhīb al-tahdhīb
darimi|ʿAbd Allāh al-Dārimī|عبد الله الدارمي|181|255|samarqand|samarqand,makkah,madinah,kufa,basra,damascus|Hadith|Traditionniste|M|Traditionniste de Samarcande|Un important Musnad/Sunan et une forte autorité régionale.|Sunan al-Dārimī|Maître du hadith de Samarcande ayant étudié dans de nombreux centres.|Son recueil conserve un ensemble ancien de traditions sur la science.|al-Dhahabī, Siyar aʿlām al-nubalāʾ§Ibn Ḥajar, Tahdhīb al-tahdhīb
daraqutni|al-Dāraquṭnī|الدارقطني|306|385|baghdad|baghdad,cairo,damascus|Hadith,Qiraat|Traditionniste|M|Critique du hadith à Bagdad|Une expertise dans les défauts subtils des chaînes de transmission.|al-Sunan§al-ʿIlal|Traditionniste bagdadien réputé pour sa mémoire et son analyse des variantes.|Il demeure une référence majeure dans la science des ʿilal.|al-Khaṭīb al-Baghdādī, Tārīkh Baghdād§al-Dhahabī, Siyar aʿlām al-nubalāʾ
bayhaqi|Aḥmad al-Bayhaqī|أحمد البيهقي|384|458|bayhaq|bayhaq,nishapur,baghdad,makkah|Hadith,Fiqh|Shafiite|M|Traditionniste du Khurasan|De vastes compilations reliant hadith et doctrine shafiite.|al-Sunan al-kubrā§Shuʿab al-īmān§Maʿrifat al-sunan wa-l-āthār|Savants du Khurasan, disciple du milieu shafiite de Nishapur.|Son œuvre est essentielle pour l’histoire documentaire du fiqh shafiite.|al-Dhahabī, Siyar aʿlām al-nubalāʾ§al-Subkī, Ṭabaqāt al-shāfiʿiyya
nawawi|Yaḥyā al-Nawawī|يحيى النووي|631|676|damascus|nawa,damascus|Hadith,Fiqh,Spiritualité|Shafiite|M|Juriste et commentateur du hadith|Des manuels d’une immense diffusion dans l’enseignement sunnite.|Riyāḍ al-ṣāliḥīn§al-Arbaʿūn§Sharḥ Ṣaḥīḥ Muslim§Minhāj al-ṭālibīn|Né à Nawa, formé et actif à Damas.|Ses ouvrages servent encore de portes d’entrée au hadith, à l’éthique et au fiqh.|Ibn al-ʿAṭṭār, Tuḥfat al-ṭālibīn§al-Dhahabī, Tadhkirat al-ḥuffāẓ
dhahabi|Shams al-Dīn al-Dhahabī|شمس الدين الذهبي|673|748|damascus|damascus,cairo,makkah,aleppo|Hadith,Biography,History|Shafiite|M|Historien des savants et critique du hadith|De grandes biographies et chroniques du monde savant.|Siyar aʿlām al-nubalāʾ§Tārīkh al-islām§Mīzān al-iʿtidāl|Traditionniste et historien de Damas, spécialiste des biographies.|Ses ouvrages structurent une grande partie de notre connaissance des réseaux savants.|al-Dhahabī, Siyar aʿlām al-nubalāʾ§Ibn Kathīr, al-Bidāya wa-l-nihāya
ibn-hajar|Aḥmad Ibn Ḥajar al-ʿAsqalānī|أحمد ابن حجر العسقلاني|773|852|cairo|cairo,makkah,madinah,damascus|Hadith,Biography,Fiqh|Shafiite|M|Commentateur du Ṣaḥīḥ al-Bukhārī|Fatḥ al-bārī et des dictionnaires biographiques de référence.|Fatḥ al-bārī§Tahdhīb al-tahdhīb§al-Iṣāba|Juge, enseignant et traditionniste du Caire mamelouk.|Son commentaire est l’un des plus influents de la tradition du hadith.|al-Sakhāwī, al-Jawāhir wa-l-durar§Ibn Ḥajar, Fatḥ al-bārī`;

    const scholars = parseRows(rows, ['id','name','arabic','born','died','city','routes','disciplines','school','gender','title','knownFor','works','bio','legacy','sources']).map((item) => ({
        ...item,
        born: Number(item.born),
        died: Number(item.died),
        routes: item.routes ? item.routes.split(',') : [],
        disciplines: item.disciplines ? item.disciplines.split(',') : [],
        works: item.works ? item.works.split('§') : [],
        sources: item.sources ? item.sources.split('§') : []
    }));

    window.SCHOLAR_ATLAS_DATA.scholars.push(...scholars);
})();
